export const cityCodes = [
  { cityCode: 5001, cityName: "MEDELLIN", codigo_departamento: 5 },
  { cityCode: 5002, cityName: "ABEJORRAL", codigo_departamento: 5 },
  { cityCode: 5004, cityName: "ABRIAQUI", codigo_departamento: 5 },
  { cityCode: 5021, cityName: "ALEJANDRIA", codigo_departamento: 5 },
  { cityCode: 5030, cityName: "AMAGA", codigo_departamento: 5 },
  { cityCode: 5031, cityName: "AMALFI", codigo_departamento: 5 },
  { cityCode: 5034, cityName: "ANDES", codigo_departamento: 5 },
  { cityCode: 5036, cityName: "ANGELOPOLIS", codigo_departamento: 5 },
  { cityCode: 5038, cityName: "ANGOSTURA", codigo_departamento: 5 },
  { cityCode: 5040, cityName: "ANORI", codigo_departamento: 5 },
  {
    cityCode: 5042,
    cityName: "SANTA FE DE ANTIOQUIA",
    codigo_departamento: 5,
  },
  { cityCode: 5044, cityName: "ANZA", codigo_departamento: 5 },
  { cityCode: 5045, cityName: "APARTADO", codigo_departamento: 5 },
  { cityCode: 5051, cityName: "ARBOLETES", codigo_departamento: 5 },
  { cityCode: 5055, cityName: "ARGELIA", codigo_departamento: 5 },
  { cityCode: 5059, cityName: "ARMENIA", codigo_departamento: 5 },
  { cityCode: 5079, cityName: "BARBOSA", codigo_departamento: 5 },
  { cityCode: 5086, cityName: "BELMIRA", codigo_departamento: 5 },
  { cityCode: 5088, cityName: "BELLO", codigo_departamento: 5 },
  { cityCode: 5091, cityName: "BETANIA", codigo_departamento: 5 },
  { cityCode: 5093, cityName: "BETULIA", codigo_departamento: 5 },
  {
    cityCode: 5101,
    cityName: "CIUDAD BOLIVAR",
    codigo_departamento: 5,
  },
  { cityCode: 5107, cityName: "BRICEÑO", codigo_departamento: 5 },
  { cityCode: 5113, cityName: "BURITICA", codigo_departamento: 5 },
  { cityCode: 5120, cityName: "CACERES", codigo_departamento: 5 },
  { cityCode: 5125, cityName: "CAICEDO", codigo_departamento: 5 },
  { cityCode: 5129, cityName: "CALDAS", codigo_departamento: 5 },
  { cityCode: 5134, cityName: "CAMPAMENTO", codigo_departamento: 5 },
  { cityCode: 5138, cityName: "CAÑASGORDAS", codigo_departamento: 5 },
  { cityCode: 5142, cityName: "CARACOLI", codigo_departamento: 5 },
  { cityCode: 5145, cityName: "CARAMANTA", codigo_departamento: 5 },
  { cityCode: 5147, cityName: "CAREPA", codigo_departamento: 5 },
  {
    cityCode: 5148,
    cityName: "EL CARMEN DE VIBORAL",
    codigo_departamento: 5,
  },
  { cityCode: 5150, cityName: "CAROLINA", codigo_departamento: 5 },
  { cityCode: 5154, cityName: "CAUCASIA", codigo_departamento: 5 },
  { cityCode: 5172, cityName: "CHIGORODO", codigo_departamento: 5 },
  { cityCode: 5190, cityName: "CISNEROS", codigo_departamento: 5 },
  { cityCode: 5197, cityName: "COCORNA", codigo_departamento: 5 },
  { cityCode: 5206, cityName: "CONCEPCION", codigo_departamento: 5 },
  { cityCode: 5209, cityName: "CONCORDIA", codigo_departamento: 5 },
  { cityCode: 5212, cityName: "COPACABANA", codigo_departamento: 5 },
  { cityCode: 5234, cityName: "DABEIBA", codigo_departamento: 5 },
  { cityCode: 5237, cityName: "DONMATIAS", codigo_departamento: 5 },
  { cityCode: 5240, cityName: "EBEJICO", codigo_departamento: 5 },
  { cityCode: 5250, cityName: "EL BAGRE", codigo_departamento: 5 },
  { cityCode: 5264, cityName: "ENTRERRIOS", codigo_departamento: 5 },
  { cityCode: 5266, cityName: "ENVIGADO", codigo_departamento: 5 },
  { cityCode: 5282, cityName: "FREDONIA", codigo_departamento: 5 },
  { cityCode: 5284, cityName: "FRONTINO", codigo_departamento: 5 },
  { cityCode: 5306, cityName: "GIRALDO", codigo_departamento: 5 },
  { cityCode: 5308, cityName: "GIRARDOTA", codigo_departamento: 5 },
  { cityCode: 5310, cityName: "GOMEZ PLATA", codigo_departamento: 5 },
  { cityCode: 5313, cityName: "GRANADA", codigo_departamento: 5 },
  { cityCode: 5315, cityName: "GUADALUPE", codigo_departamento: 5 },
  { cityCode: 5318, cityName: "GUARNE", codigo_departamento: 5 },
  { cityCode: 5321, cityName: "GUATAPE", codigo_departamento: 5 },
  { cityCode: 5347, cityName: "HELICONIA", codigo_departamento: 5 },
  { cityCode: 5353, cityName: "HISPANIA", codigo_departamento: 5 },
  { cityCode: 5360, cityName: "ITAGÜI", codigo_departamento: 5 },
  { cityCode: 5361, cityName: "ITUANGO", codigo_departamento: 5 },
  { cityCode: 5364, cityName: "JARDIN", codigo_departamento: 5 },
  { cityCode: 5368, cityName: "JERICO", codigo_departamento: 5 },
  { cityCode: 5376, cityName: "LA CEJA", codigo_departamento: 5 },
  { cityCode: 5380, cityName: "LA ESTRELLA", codigo_departamento: 5 },
  { cityCode: 5390, cityName: "LA PINTADA", codigo_departamento: 5 },
  { cityCode: 5400, cityName: "LA UNION", codigo_departamento: 5 },
  { cityCode: 5411, cityName: "LIBORINA", codigo_departamento: 5 },
  { cityCode: 5425, cityName: "MACEO", codigo_departamento: 5 },
  { cityCode: 5440, cityName: "MARINILLA", codigo_departamento: 5 },
  { cityCode: 5467, cityName: "MONTEBELLO", codigo_departamento: 5 },
  { cityCode: 5475, cityName: "MURINDO", codigo_departamento: 5 },
  { cityCode: 5480, cityName: "MUTATA", codigo_departamento: 5 },
  { cityCode: 5483, cityName: "NARIÑO", codigo_departamento: 5 },
  { cityCode: 5490, cityName: "NECOCLI", codigo_departamento: 5 },
  { cityCode: 5495, cityName: "NECHI", codigo_departamento: 5 },
  { cityCode: 5501, cityName: "OLAYA", codigo_departamento: 5 },
  { cityCode: 5541, cityName: "PEÑOL", codigo_departamento: 5 },
  { cityCode: 5543, cityName: "PEQUE", codigo_departamento: 5 },
  { cityCode: 5576, cityName: "PUEBLORRICO", codigo_departamento: 5 },
  {
    cityCode: 5579,
    cityName: "PUERTO BERRIO",
    codigo_departamento: 5,
  },
  { cityCode: 5585, cityName: "PUERTO NARE", codigo_departamento: 5 },
  {
    cityCode: 5591,
    cityName: "PUERTO TRIUNFO",
    codigo_departamento: 5,
  },
  { cityCode: 5604, cityName: "REMEDIOS", codigo_departamento: 5 },
  { cityCode: 5607, cityName: "RETIRO", codigo_departamento: 5 },
  { cityCode: 5615, cityName: "RIONEGRO", codigo_departamento: 5 },
  { cityCode: 5628, cityName: "SABANALARGA", codigo_departamento: 5 },
  { cityCode: 5631, cityName: "SABANETA", codigo_departamento: 5 },
  { cityCode: 5642, cityName: "SALGAR", codigo_departamento: 5 },
  {
    cityCode: 5647,
    cityName: "SAN ANDRES DE CUERQUIA",
    codigo_departamento: 5,
  },
  { cityCode: 5649, cityName: "SAN CARLOS", codigo_departamento: 5 },
  {
    cityCode: 5652,
    cityName: "SAN FRANCISCO",
    codigo_departamento: 5,
  },
  {
    cityCode: 5656,
    cityName: "SAN JERONIMO",
    codigo_departamento: 5,
  },
  {
    cityCode: 5658,
    cityName: "SAN JOSE DE LA MONTAÑA",
    codigo_departamento: 5,
  },
  {
    cityCode: 5659,
    cityName: "SAN JUAN DE URABA",
    codigo_departamento: 5,
  },
  { cityCode: 5660, cityName: "SAN LUIS", codigo_departamento: 5 },
  {
    cityCode: 5664,
    cityName: "SAN PEDRO DE LOS MILAGROS",
    codigo_departamento: 5,
  },
  {
    cityCode: 5665,
    cityName: "SAN PEDRO DE URABA",
    codigo_departamento: 5,
  },
  { cityCode: 5667, cityName: "SAN RAFAEL", codigo_departamento: 5 },
  { cityCode: 5670, cityName: "SAN ROQUE", codigo_departamento: 5 },
  {
    cityCode: 5674,
    cityName: "SAN VICENTE FERRER",
    codigo_departamento: 5,
  },
  {
    cityCode: 5679,
    cityName: "SANTA BARBARA",
    codigo_departamento: 5,
  },
  {
    cityCode: 5686,
    cityName: "SANTA ROSA DE OSOS",
    codigo_departamento: 5,
  },
  {
    cityCode: 5690,
    cityName: "SANTO DOMINGO",
    codigo_departamento: 5,
  },
  {
    cityCode: 5697,
    cityName: "EL SANTUARIO",
    codigo_departamento: 5,
  },
  { cityCode: 5736, cityName: "SEGOVIA", codigo_departamento: 5 },
  { cityCode: 5756, cityName: "SONSON", codigo_departamento: 5 },
  { cityCode: 5761, cityName: "SOPETRAN", codigo_departamento: 5 },
  { cityCode: 5789, cityName: "TAMESIS", codigo_departamento: 5 },
  { cityCode: 5790, cityName: "TARAZA", codigo_departamento: 5 },
  { cityCode: 5792, cityName: "TARSO", codigo_departamento: 5 },
  { cityCode: 5809, cityName: "TITIRIBI", codigo_departamento: 5 },
  { cityCode: 5819, cityName: "TOLEDO", codigo_departamento: 5 },
  { cityCode: 5837, cityName: "TURBO", codigo_departamento: 5 },
  { cityCode: 5842, cityName: "URAMITA", codigo_departamento: 5 },
  { cityCode: 5847, cityName: "URRAO", codigo_departamento: 5 },
  { cityCode: 5854, cityName: "VALDIVIA", codigo_departamento: 5 },
  { cityCode: 5856, cityName: "VALPARAISO", codigo_departamento: 5 },
  { cityCode: 5858, cityName: "VEGACHI", codigo_departamento: 5 },
  { cityCode: 5861, cityName: "VENECIA", codigo_departamento: 5 },
  {
    cityCode: 5873,
    cityName: "VIGIA DEL FUERTE",
    codigo_departamento: 5,
  },
  { cityCode: 5885, cityName: "YALI", codigo_departamento: 5 },
  { cityCode: 5887, cityName: "YARUMAL", codigo_departamento: 5 },
  { cityCode: 5890, cityName: "YOLOMBO", codigo_departamento: 5 },
  { cityCode: 5893, cityName: "YONDO", codigo_departamento: 5 },
  { cityCode: 5895, cityName: "ZARAGOZA", codigo_departamento: 5 },
  {
    cityCode: 8001,
    cityName: "BARRANQUILLA",
    codigo_departamento: 8,
  },
  { cityCode: 8078, cityName: "BARANOA", codigo_departamento: 8 },
  {
    cityCode: 8137,
    cityName: "CAMPO DE LA CRUZ",
    codigo_departamento: 8,
  },
  { cityCode: 8141, cityName: "CANDELARIA", codigo_departamento: 8 },
  { cityCode: 8296, cityName: "GALAPA", codigo_departamento: 8 },
  {
    cityCode: 8372,
    cityName: "JUAN DE ACOSTA",
    codigo_departamento: 8,
  },
  { cityCode: 8421, cityName: "LURUACO", codigo_departamento: 8 },
  { cityCode: 8433, cityName: "MALAMBO", codigo_departamento: 8 },
  { cityCode: 8436, cityName: "MANATI", codigo_departamento: 8 },
  {
    cityCode: 8520,
    cityName: "PALMAR DE VARELA",
    codigo_departamento: 8,
  },
  { cityCode: 8549, cityName: "PIOJO", codigo_departamento: 8 },
  { cityCode: 8558, cityName: "POLONUEVO", codigo_departamento: 8 },
  { cityCode: 8560, cityName: "PONEDERA", codigo_departamento: 8 },
  {
    cityCode: 8573,
    cityName: "PUERTO COLOMBIA",
    codigo_departamento: 8,
  },
  { cityCode: 8606, cityName: "REPELON", codigo_departamento: 8 },
  {
    cityCode: 8634,
    cityName: "SABANAGRANDE",
    codigo_departamento: 8,
  },
  { cityCode: 8638, cityName: "SABANALARGA", codigo_departamento: 8 },
  { cityCode: 8675, cityName: "SANTA LUCIA", codigo_departamento: 8 },
  { cityCode: 8685, cityName: "SANTO TOMAS", codigo_departamento: 8 },
  { cityCode: 8758, cityName: "SOLEDAD", codigo_departamento: 8 },
  { cityCode: 8770, cityName: "SUAN", codigo_departamento: 8 },
  { cityCode: 8832, cityName: "TUBARA", codigo_departamento: 8 },
  { cityCode: 8849, cityName: "USIACURI", codigo_departamento: 8 },
  {
    cityCode: 11001,
    cityName: "BOGOTA. D.C.",
    codigo_departamento: 11,
  },
  {
    cityCode: 13001,
    cityName: "CARTAGENA DE INDIAS",
    codigo_departamento: 13,
  },
  { cityCode: 13006, cityName: "ACHI", codigo_departamento: 13 },
  {
    cityCode: 13030,
    cityName: "ALTOS DEL ROSARIO",
    codigo_departamento: 13,
  },
  { cityCode: 13042, cityName: "ARENAL", codigo_departamento: 13 },
  { cityCode: 13052, cityName: "ARJONA", codigo_departamento: 13 },
  {
    cityCode: 13062,
    cityName: "ARROYOHONDO",
    codigo_departamento: 13,
  },
  {
    cityCode: 13074,
    cityName: "BARRANCO DE LOBA",
    codigo_departamento: 13,
  },
  { cityCode: 13140, cityName: "CALAMAR", codigo_departamento: 13 },
  {
    cityCode: 13160,
    cityName: "CANTAGALLO",
    codigo_departamento: 13,
  },
  { cityCode: 13188, cityName: "CICUCO", codigo_departamento: 13 },
  { cityCode: 13212, cityName: "CORDOBA", codigo_departamento: 13 },
  { cityCode: 13222, cityName: "CLEMENCIA", codigo_departamento: 13 },
  {
    cityCode: 13244,
    cityName: "EL CARMEN DE BOLIVAR",
    codigo_departamento: 13,
  },
  { cityCode: 13248, cityName: "EL GUAMO", codigo_departamento: 13 },
  { cityCode: 13268, cityName: "EL PEÑON", codigo_departamento: 13 },
  {
    cityCode: 13300,
    cityName: "HATILLO DE LOBA",
    codigo_departamento: 13,
  },
  { cityCode: 13430, cityName: "MAGANGUE", codigo_departamento: 13 },
  { cityCode: 13433, cityName: "MAHATES", codigo_departamento: 13 },
  { cityCode: 13440, cityName: "MARGARITA", codigo_departamento: 13 },
  {
    cityCode: 13442,
    cityName: "MARIA LA BAJA",
    codigo_departamento: 13,
  },
  {
    cityCode: 13458,
    cityName: "MONTECRISTO",
    codigo_departamento: 13,
  },
  {
    cityCode: 13468,
    cityName: "SANTA CRUZ DE MOMPOX",
    codigo_departamento: 13,
  },
  { cityCode: 13473, cityName: "MORALES", codigo_departamento: 13 },
  { cityCode: 13490, cityName: "NOROSI", codigo_departamento: 13 },
  { cityCode: 13549, cityName: "PINILLOS", codigo_departamento: 13 },
  { cityCode: 13580, cityName: "REGIDOR", codigo_departamento: 13 },
  { cityCode: 13600, cityName: "RIO VIEJO", codigo_departamento: 13 },
  {
    cityCode: 13620,
    cityName: "SAN CRISTOBAL",
    codigo_departamento: 13,
  },
  {
    cityCode: 13647,
    cityName: "SAN ESTANISLAO",
    codigo_departamento: 13,
  },
  {
    cityCode: 13650,
    cityName: "SAN FERNANDO",
    codigo_departamento: 13,
  },
  {
    cityCode: 13654,
    cityName: "SAN JACINTO",
    codigo_departamento: 13,
  },
  {
    cityCode: 13655,
    cityName: "SAN JACINTO DEL CAUCA",
    codigo_departamento: 13,
  },
  {
    cityCode: 13657,
    cityName: "SAN JUAN NEPOMUCENO",
    codigo_departamento: 13,
  },
  {
    cityCode: 13667,
    cityName: "SAN MARTIN DE LOBA",
    codigo_departamento: 13,
  },
  { cityCode: 13670, cityName: "SAN PABLO", codigo_departamento: 13 },
  {
    cityCode: 13673,
    cityName: "SANTA CATALINA",
    codigo_departamento: 13,
  },
  {
    cityCode: 13683,
    cityName: "SANTA ROSA",
    codigo_departamento: 13,
  },
  {
    cityCode: 13688,
    cityName: "SANTA ROSA DEL SUR",
    codigo_departamento: 13,
  },
  { cityCode: 13744, cityName: "SIMITI", codigo_departamento: 13 },
  {
    cityCode: 13760,
    cityName: "SOPLAVIENTO",
    codigo_departamento: 13,
  },
  {
    cityCode: 13780,
    cityName: "TALAIGUA NUEVO",
    codigo_departamento: 13,
  },
  { cityCode: 13810, cityName: "TIQUISIO", codigo_departamento: 13 },
  { cityCode: 13836, cityName: "TURBACO", codigo_departamento: 13 },
  { cityCode: 13838, cityName: "TURBANA", codigo_departamento: 13 },
  {
    cityCode: 13873,
    cityName: "VILLANUEVA",
    codigo_departamento: 13,
  },
  { cityCode: 13894, cityName: "ZAMBRANO", codigo_departamento: 13 },
  { cityCode: 15001, cityName: "TUNJA", codigo_departamento: 15 },
  { cityCode: 15022, cityName: "ALMEIDA", codigo_departamento: 15 },
  { cityCode: 15047, cityName: "AQUITANIA", codigo_departamento: 15 },
  { cityCode: 15051, cityName: "ARCABUCO", codigo_departamento: 15 },
  { cityCode: 15087, cityName: "BELEN", codigo_departamento: 15 },
  { cityCode: 15090, cityName: "BERBEO", codigo_departamento: 15 },
  { cityCode: 15092, cityName: "BETEITIVA", codigo_departamento: 15 },
  { cityCode: 15097, cityName: "BOAVITA", codigo_departamento: 15 },
  { cityCode: 15104, cityName: "BOYACA", codigo_departamento: 15 },
  { cityCode: 15106, cityName: "BRICEÑO", codigo_departamento: 15 },
  {
    cityCode: 15109,
    cityName: "BUENAVISTA",
    codigo_departamento: 15,
  },
  { cityCode: 15114, cityName: "BUSBANZA", codigo_departamento: 15 },
  { cityCode: 15131, cityName: "CALDAS", codigo_departamento: 15 },
  {
    cityCode: 15135,
    cityName: "CAMPOHERMOSO",
    codigo_departamento: 15,
  },
  { cityCode: 15162, cityName: "CERINZA", codigo_departamento: 15 },
  { cityCode: 15172, cityName: "CHINAVITA", codigo_departamento: 15 },
  {
    cityCode: 15176,
    cityName: "CHIQUINQUIRA",
    codigo_departamento: 15,
  },
  { cityCode: 15180, cityName: "CHISCAS", codigo_departamento: 15 },
  { cityCode: 15183, cityName: "CHITA", codigo_departamento: 15 },
  {
    cityCode: 15185,
    cityName: "CHITARAQUE",
    codigo_departamento: 15,
  },
  { cityCode: 15187, cityName: "CHIVATA", codigo_departamento: 15 },
  { cityCode: 15189, cityName: "CIENEGA", codigo_departamento: 15 },
  { cityCode: 15204, cityName: "COMBITA", codigo_departamento: 15 },
  { cityCode: 15212, cityName: "COPER", codigo_departamento: 15 },
  { cityCode: 15215, cityName: "CORRALES", codigo_departamento: 15 },
  {
    cityCode: 15218,
    cityName: "COVARACHIA",
    codigo_departamento: 15,
  },
  { cityCode: 15223, cityName: "CUBARA", codigo_departamento: 15 },
  { cityCode: 19318, cityName: "GUAPI", codigo_departamento: 19 },
  { cityCode: 15224, cityName: "CUCAITA", codigo_departamento: 15 },
  { cityCode: 15226, cityName: "CUITIVA", codigo_departamento: 15 },
  { cityCode: 15232, cityName: "CHIQUIZA", codigo_departamento: 15 },
  { cityCode: 15236, cityName: "CHIVOR", codigo_departamento: 15 },
  { cityCode: 15238, cityName: "DUITAMA", codigo_departamento: 15 },
  { cityCode: 15244, cityName: "EL COCUY", codigo_departamento: 15 },
  { cityCode: 15248, cityName: "EL ESPINO", codigo_departamento: 15 },
  {
    cityCode: 15272,
    cityName: "FIRAVITOBA",
    codigo_departamento: 15,
  },
  { cityCode: 15276, cityName: "FLORESTA", codigo_departamento: 15 },
  {
    cityCode: 15293,
    cityName: "GACHANTIVA",
    codigo_departamento: 15,
  },
  { cityCode: 15296, cityName: "GAMEZA", codigo_departamento: 15 },
  { cityCode: 15299, cityName: "GARAGOA", codigo_departamento: 15 },
  {
    cityCode: 15317,
    cityName: "GUACAMAYAS",
    codigo_departamento: 15,
  },
  { cityCode: 15322, cityName: "GUATEQUE", codigo_departamento: 15 },
  { cityCode: 15325, cityName: "GUAYATA", codigo_departamento: 15 },
  {
    cityCode: 15332,
    cityName: "GÜICAN DE LA SIERRA",
    codigo_departamento: 15,
  },
  { cityCode: 15362, cityName: "IZA", codigo_departamento: 15 },
  { cityCode: 15367, cityName: "JENESANO", codigo_departamento: 15 },
  { cityCode: 15368, cityName: "JERICO", codigo_departamento: 15 },
  {
    cityCode: 15377,
    cityName: "LABRANZAGRANDE",
    codigo_departamento: 15,
  },
  {
    cityCode: 15380,
    cityName: "LA CAPILLA",
    codigo_departamento: 15,
  },
  {
    cityCode: 15401,
    cityName: "LA VICTORIA",
    codigo_departamento: 15,
  },
  { cityCode: 15403, cityName: "LA UVITA", codigo_departamento: 15 },
  {
    cityCode: 15407,
    cityName: "VILLA DE LEYVA",
    codigo_departamento: 15,
  },
  { cityCode: 15425, cityName: "MACANAL", codigo_departamento: 15 },
  { cityCode: 15442, cityName: "MARIPI", codigo_departamento: 15 },
  {
    cityCode: 15455,
    cityName: "MIRAFLORES",
    codigo_departamento: 15,
  },
  { cityCode: 15464, cityName: "MONGUA", codigo_departamento: 15 },
  { cityCode: 15466, cityName: "MONGUI", codigo_departamento: 15 },
  { cityCode: 15469, cityName: "MONIQUIRA", codigo_departamento: 15 },
  { cityCode: 15476, cityName: "MOTAVITA", codigo_departamento: 15 },
  { cityCode: 15480, cityName: "MUZO", codigo_departamento: 15 },
  { cityCode: 15491, cityName: "NOBSA", codigo_departamento: 15 },
  {
    cityCode: 15494,
    cityName: "NUEVO COLON",
    codigo_departamento: 15,
  },
  { cityCode: 15500, cityName: "OICATA", codigo_departamento: 15 },
  { cityCode: 15507, cityName: "OTANCHE", codigo_departamento: 15 },
  { cityCode: 15511, cityName: "PACHAVITA", codigo_departamento: 15 },
  { cityCode: 15514, cityName: "PAEZ", codigo_departamento: 15 },
  { cityCode: 15516, cityName: "PAIPA", codigo_departamento: 15 },
  { cityCode: 15518, cityName: "PAJARITO", codigo_departamento: 15 },
  { cityCode: 15522, cityName: "PANQUEBA", codigo_departamento: 15 },
  { cityCode: 15531, cityName: "PAUNA", codigo_departamento: 15 },
  { cityCode: 15533, cityName: "PAYA", codigo_departamento: 15 },
  {
    cityCode: 15537,
    cityName: "PAZ DE RIO",
    codigo_departamento: 15,
  },
  { cityCode: 15542, cityName: "PESCA", codigo_departamento: 15 },
  { cityCode: 15550, cityName: "PISBA", codigo_departamento: 15 },
  {
    cityCode: 15572,
    cityName: "PUERTO BOYACA",
    codigo_departamento: 15,
  },
  { cityCode: 15580, cityName: "QUIPAMA", codigo_departamento: 15 },
  { cityCode: 15599, cityName: "RAMIRIQUI", codigo_departamento: 15 },
  { cityCode: 15600, cityName: "RAQUIRA", codigo_departamento: 15 },
  { cityCode: 15621, cityName: "RONDON", codigo_departamento: 15 },
  { cityCode: 15632, cityName: "SABOYA", codigo_departamento: 15 },
  { cityCode: 15638, cityName: "SACHICA", codigo_departamento: 15 },
  { cityCode: 15646, cityName: "SAMACA", codigo_departamento: 15 },
  {
    cityCode: 15660,
    cityName: "SAN EDUARDO",
    codigo_departamento: 15,
  },
  {
    cityCode: 15664,
    cityName: "SAN JOSE DE PARE",
    codigo_departamento: 15,
  },
  {
    cityCode: 15667,
    cityName: "SAN LUIS DE GACENO",
    codigo_departamento: 15,
  },
  { cityCode: 15673, cityName: "SAN MATEO", codigo_departamento: 15 },
  {
    cityCode: 15676,
    cityName: "SAN MIGUEL DE SEMA",
    codigo_departamento: 15,
  },
  {
    cityCode: 15681,
    cityName: "SAN PABLO DE BORBUR",
    codigo_departamento: 15,
  },
  { cityCode: 15686, cityName: "SANTANA", codigo_departamento: 15 },
  {
    cityCode: 15690,
    cityName: "SANTA MARIA",
    codigo_departamento: 15,
  },
  {
    cityCode: 15693,
    cityName: "SANTA ROSA DE VITERBO",
    codigo_departamento: 15,
  },
  {
    cityCode: 15696,
    cityName: "SANTA SOFIA",
    codigo_departamento: 15,
  },
  {
    cityCode: 15720,
    cityName: "SATIVANORTE",
    codigo_departamento: 15,
  },
  { cityCode: 15723, cityName: "SATIVASUR", codigo_departamento: 15 },
  { cityCode: 15740, cityName: "SIACHOQUE", codigo_departamento: 15 },
  { cityCode: 15753, cityName: "SOATA", codigo_departamento: 15 },
  { cityCode: 15755, cityName: "SOCOTA", codigo_departamento: 15 },
  { cityCode: 15757, cityName: "SOCHA", codigo_departamento: 15 },
  { cityCode: 15759, cityName: "SOGAMOSO", codigo_departamento: 15 },
  { cityCode: 15761, cityName: "SOMONDOCO", codigo_departamento: 15 },
  { cityCode: 15762, cityName: "SORA", codigo_departamento: 15 },
  { cityCode: 15763, cityName: "SOTAQUIRA", codigo_departamento: 15 },
  { cityCode: 15764, cityName: "SORACA", codigo_departamento: 15 },
  { cityCode: 15774, cityName: "SUSACON", codigo_departamento: 15 },
  {
    cityCode: 15776,
    cityName: "SUTAMARCHAN",
    codigo_departamento: 15,
  },
  { cityCode: 15778, cityName: "SUTATENZA", codigo_departamento: 15 },
  { cityCode: 15790, cityName: "TASCO", codigo_departamento: 15 },
  { cityCode: 15798, cityName: "TENZA", codigo_departamento: 15 },
  { cityCode: 15804, cityName: "TIBANA", codigo_departamento: 15 },
  { cityCode: 15806, cityName: "TIBASOSA", codigo_departamento: 15 },
  { cityCode: 15808, cityName: "TINJACA", codigo_departamento: 15 },
  { cityCode: 15810, cityName: "TIPACOQUE", codigo_departamento: 15 },
  { cityCode: 15814, cityName: "TOCA", codigo_departamento: 15 },
  { cityCode: 15816, cityName: "TOGÜI", codigo_departamento: 15 },
  { cityCode: 15820, cityName: "TOPAGA", codigo_departamento: 15 },
  { cityCode: 15822, cityName: "TOTA", codigo_departamento: 15 },
  { cityCode: 15832, cityName: "TUNUNGUA", codigo_departamento: 15 },
  { cityCode: 15835, cityName: "TURMEQUE", codigo_departamento: 15 },
  { cityCode: 15837, cityName: "TUTA", codigo_departamento: 15 },
  { cityCode: 15839, cityName: "TUTAZA", codigo_departamento: 15 },
  { cityCode: 15842, cityName: "UMBITA", codigo_departamento: 15 },
  {
    cityCode: 15861,
    cityName: "VENTAQUEMADA",
    codigo_departamento: 15,
  },
  { cityCode: 15879, cityName: "VIRACACHA", codigo_departamento: 15 },
  { cityCode: 15897, cityName: "ZETAQUIRA", codigo_departamento: 15 },
  { cityCode: 17001, cityName: "MANIZALES", codigo_departamento: 17 },
  { cityCode: 17013, cityName: "AGUADAS", codigo_departamento: 17 },
  { cityCode: 17042, cityName: "ANSERMA", codigo_departamento: 17 },
  { cityCode: 17050, cityName: "ARANZAZU", codigo_departamento: 17 },
  {
    cityCode: 17088,
    cityName: "BELALCAZAR",
    codigo_departamento: 17,
  },
  { cityCode: 17174, cityName: "CHINCHINA", codigo_departamento: 17 },
  {
    cityCode: 17272,
    cityName: "FILADELFIA",
    codigo_departamento: 17,
  },
  { cityCode: 17380, cityName: "LA DORADA", codigo_departamento: 17 },
  { cityCode: 17388, cityName: "LA MERCED", codigo_departamento: 17 },
  {
    cityCode: 17433,
    cityName: "MANZANARES",
    codigo_departamento: 17,
  },
  { cityCode: 17442, cityName: "MARMATO", codigo_departamento: 17 },
  {
    cityCode: 17444,
    cityName: "MARQUETALIA",
    codigo_departamento: 17,
  },
  { cityCode: 17446, cityName: "MARULANDA", codigo_departamento: 17 },
  { cityCode: 17486, cityName: "NEIRA", codigo_departamento: 17 },
  { cityCode: 17495, cityName: "NORCASIA", codigo_departamento: 17 },
  { cityCode: 17513, cityName: "PACORA", codigo_departamento: 17 },
  { cityCode: 17524, cityName: "PALESTINA", codigo_departamento: 17 },
  {
    cityCode: 17541,
    cityName: "PENSILVANIA",
    codigo_departamento: 17,
  },
  { cityCode: 17614, cityName: "RIOSUCIO", codigo_departamento: 17 },
  { cityCode: 17616, cityName: "RISARALDA", codigo_departamento: 17 },
  { cityCode: 17653, cityName: "SALAMINA", codigo_departamento: 17 },
  { cityCode: 17662, cityName: "SAMANA", codigo_departamento: 17 },
  { cityCode: 17665, cityName: "SAN JOSE", codigo_departamento: 17 },
  { cityCode: 17777, cityName: "SUPIA", codigo_departamento: 17 },
  { cityCode: 17867, cityName: "VICTORIA", codigo_departamento: 17 },
  {
    cityCode: 17873,
    cityName: "VILLAMARIA",
    codigo_departamento: 17,
  },
  { cityCode: 17877, cityName: "VITERBO", codigo_departamento: 17 },
  { cityCode: 18001, cityName: "FLORENCIA", codigo_departamento: 18 },
  { cityCode: 18029, cityName: "ALBANIA", codigo_departamento: 18 },
  {
    cityCode: 18094,
    cityName: "BELEN DE LOS ANDAQUIES",
    codigo_departamento: 18,
  },
  {
    cityCode: 18150,
    cityName: "CARTAGENA DEL CHAIRA",
    codigo_departamento: 18,
  },
  { cityCode: 18205, cityName: "CURILLO", codigo_departamento: 18 },
  {
    cityCode: 18247,
    cityName: "EL DONCELLO",
    codigo_departamento: 18,
  },
  { cityCode: 18256, cityName: "EL PAUJIL", codigo_departamento: 18 },
  {
    cityCode: 18410,
    cityName: "LA MONTAÑITA",
    codigo_departamento: 18,
  },
  { cityCode: 18460, cityName: "MILAN", codigo_departamento: 18 },
  { cityCode: 18479, cityName: "MORELIA", codigo_departamento: 18 },
  {
    cityCode: 18592,
    cityName: "PUERTO RICO",
    codigo_departamento: 18,
  },
  {
    cityCode: 18610,
    cityName: "SAN JOSE DEL FRAGUA",
    codigo_departamento: 18,
  },
  {
    cityCode: 18753,
    cityName: "SAN VICENTE DEL CAGUAN",
    codigo_departamento: 18,
  },
  { cityCode: 18756, cityName: "SOLANO", codigo_departamento: 18 },
  { cityCode: 18785, cityName: "SOLITA", codigo_departamento: 18 },
  {
    cityCode: 18860,
    cityName: "VALPARAISO",
    codigo_departamento: 18,
  },
  { cityCode: 19001, cityName: "POPAYAN", codigo_departamento: 19 },
  { cityCode: 19022, cityName: "ALMAGUER", codigo_departamento: 19 },
  { cityCode: 19050, cityName: "ARGELIA", codigo_departamento: 19 },
  { cityCode: 19075, cityName: "BALBOA", codigo_departamento: 19 },
  { cityCode: 19100, cityName: "BOLIVAR", codigo_departamento: 19 },
  {
    cityCode: 19110,
    cityName: "BUENOS AIRES",
    codigo_departamento: 19,
  },
  { cityCode: 19130, cityName: "CAJIBIO", codigo_departamento: 19 },
  { cityCode: 19137, cityName: "CALDONO", codigo_departamento: 19 },
  { cityCode: 19142, cityName: "CALOTO", codigo_departamento: 19 },
  { cityCode: 19212, cityName: "CORINTO", codigo_departamento: 19 },
  { cityCode: 19256, cityName: "EL TAMBO", codigo_departamento: 19 },
  { cityCode: 19290, cityName: "FLORENCIA", codigo_departamento: 19 },
  { cityCode: 19300, cityName: "GUACHENE", codigo_departamento: 19 },
  { cityCode: 19355, cityName: "INZA", codigo_departamento: 19 },
  { cityCode: 19364, cityName: "JAMBALO", codigo_departamento: 19 },
  { cityCode: 19392, cityName: "LA SIERRA", codigo_departamento: 19 },
  { cityCode: 19397, cityName: "LA VEGA", codigo_departamento: 19 },
  {
    cityCode: 19418,
    cityName: "LOPEZ DE MICAY",
    codigo_departamento: 19,
  },
  {
    cityCode: 19450,
    cityName: "MERCADERES",
    codigo_departamento: 19,
  },
  { cityCode: 19455, cityName: "MIRANDA", codigo_departamento: 19 },
  { cityCode: 19473, cityName: "MORALES", codigo_departamento: 19 },
  { cityCode: 19513, cityName: "PADILLA", codigo_departamento: 19 },
  { cityCode: 19517, cityName: "PAEZ", codigo_departamento: 19 },
  { cityCode: 19532, cityName: "PATIA", codigo_departamento: 19 },
  { cityCode: 19533, cityName: "PIAMONTE", codigo_departamento: 19 },
  {
    cityCode: 19548,
    cityName: "PIENDAMO - TUNIA",
    codigo_departamento: 19,
  },
  {
    cityCode: 19573,
    cityName: "PUERTO TEJADA",
    codigo_departamento: 19,
  },
  { cityCode: 19585, cityName: "PURACE", codigo_departamento: 19 },
  { cityCode: 19622, cityName: "ROSAS", codigo_departamento: 19 },
  {
    cityCode: 19693,
    cityName: "SAN SEBASTIAN",
    codigo_departamento: 19,
  },
  {
    cityCode: 19698,
    cityName: "SANTANDER DE QUILICHAO",
    codigo_departamento: 19,
  },
  {
    cityCode: 19701,
    cityName: "SANTA ROSA",
    codigo_departamento: 19,
  },
  { cityCode: 19743, cityName: "SILVIA", codigo_departamento: 19 },
  {
    cityCode: 19760,
    cityName: "SOTARA PAISPAMBA",
    codigo_departamento: 19,
  },
  { cityCode: 19780, cityName: "SUAREZ", codigo_departamento: 19 },
  { cityCode: 19785, cityName: "SUCRE", codigo_departamento: 19 },
  { cityCode: 19807, cityName: "TIMBIO", codigo_departamento: 19 },
  { cityCode: 19809, cityName: "TIMBIQUI", codigo_departamento: 19 },
  { cityCode: 19821, cityName: "TORIBIO", codigo_departamento: 19 },
  { cityCode: 19824, cityName: "TOTORO", codigo_departamento: 19 },
  {
    cityCode: 19845,
    cityName: "VILLA RICA",
    codigo_departamento: 19,
  },
  {
    cityCode: 20001,
    cityName: "VALLEDUPAR",
    codigo_departamento: 20,
  },
  { cityCode: 20011, cityName: "AGUACHICA", codigo_departamento: 20 },
  {
    cityCode: 20013,
    cityName: "AGUSTIN CODAZZI",
    codigo_departamento: 20,
  },
  { cityCode: 20032, cityName: "ASTREA", codigo_departamento: 20 },
  { cityCode: 20045, cityName: "BECERRIL", codigo_departamento: 20 },
  { cityCode: 20060, cityName: "BOSCONIA", codigo_departamento: 20 },
  {
    cityCode: 20175,
    cityName: "CHIMICHAGUA",
    codigo_departamento: 20,
  },
  {
    cityCode: 20178,
    cityName: "CHIRIGUANA",
    codigo_departamento: 20,
  },
  { cityCode: 20228, cityName: "CURUMANI", codigo_departamento: 20 },
  { cityCode: 20238, cityName: "EL COPEY", codigo_departamento: 20 },
  { cityCode: 20250, cityName: "EL PASO", codigo_departamento: 20 },
  { cityCode: 20295, cityName: "GAMARRA", codigo_departamento: 20 },
  { cityCode: 20310, cityName: "GONZALEZ", codigo_departamento: 20 },
  { cityCode: 20383, cityName: "LA GLORIA", codigo_departamento: 20 },
  {
    cityCode: 20400,
    cityName: "LA JAGUA DE IBIRICO",
    codigo_departamento: 20,
  },
  {
    cityCode: 20443,
    cityName: "MANAURE BALCON DEL CESAR",
    codigo_departamento: 20,
  },
  { cityCode: 20517, cityName: "PAILITAS", codigo_departamento: 20 },
  { cityCode: 20550, cityName: "PELAYA", codigo_departamento: 20 },
  {
    cityCode: 20570,
    cityName: "PUEBLO BELLO",
    codigo_departamento: 20,
  },
  {
    cityCode: 20614,
    cityName: "RIO DE ORO",
    codigo_departamento: 20,
  },
  { cityCode: 20621, cityName: "LA PAZ", codigo_departamento: 20 },
  {
    cityCode: 20710,
    cityName: "SAN ALBERTO",
    codigo_departamento: 20,
  },
  { cityCode: 20750, cityName: "SAN DIEGO", codigo_departamento: 20 },
  {
    cityCode: 20770,
    cityName: "SAN MARTIN",
    codigo_departamento: 20,
  },
  {
    cityCode: 20787,
    cityName: "TAMALAMEQUE",
    codigo_departamento: 20,
  },
  { cityCode: 23001, cityName: "MONTERIA", codigo_departamento: 23 },
  { cityCode: 23068, cityName: "AYAPEL", codigo_departamento: 23 },
  {
    cityCode: 23079,
    cityName: "BUENAVISTA",
    codigo_departamento: 23,
  },
  { cityCode: 23090, cityName: "CANALETE", codigo_departamento: 23 },
  { cityCode: 23162, cityName: "CERETE", codigo_departamento: 23 },
  { cityCode: 23168, cityName: "CHIMA", codigo_departamento: 23 },
  { cityCode: 23182, cityName: "CHINU", codigo_departamento: 23 },
  {
    cityCode: 23189,
    cityName: "CIENAGA DE ORO",
    codigo_departamento: 23,
  },
  { cityCode: 23300, cityName: "COTORRA", codigo_departamento: 23 },
  {
    cityCode: 23350,
    cityName: "LA APARTADA",
    codigo_departamento: 23,
  },
  { cityCode: 23417, cityName: "LORICA", codigo_departamento: 23 },
  {
    cityCode: 23419,
    cityName: "LOS CORDOBAS",
    codigo_departamento: 23,
  },
  { cityCode: 23464, cityName: "MOMIL", codigo_departamento: 23 },
  {
    cityCode: 23466,
    cityName: "MONTELIBANO",
    codigo_departamento: 23,
  },
  { cityCode: 23500, cityName: "MOÑITOS", codigo_departamento: 23 },
  {
    cityCode: 23555,
    cityName: "PLANETA RICA",
    codigo_departamento: 23,
  },
  {
    cityCode: 23570,
    cityName: "PUEBLO NUEVO",
    codigo_departamento: 23,
  },
  {
    cityCode: 23574,
    cityName: "PUERTO ESCONDIDO",
    codigo_departamento: 23,
  },
  {
    cityCode: 23580,
    cityName: "PUERTO LIBERTADOR",
    codigo_departamento: 23,
  },
  {
    cityCode: 23586,
    cityName: "PURISIMA DE LA CONCEPCION",
    codigo_departamento: 23,
  },
  { cityCode: 23660, cityName: "SAHAGUN", codigo_departamento: 23 },
  {
    cityCode: 23670,
    cityName: "SAN ANDRES DE SOTAVENTO",
    codigo_departamento: 23,
  },
  {
    cityCode: 23672,
    cityName: "SAN ANTERO",
    codigo_departamento: 23,
  },
  {
    cityCode: 23675,
    cityName: "SAN BERNARDO DEL VIENTO",
    codigo_departamento: 23,
  },
  {
    cityCode: 23678,
    cityName: "SAN CARLOS",
    codigo_departamento: 23,
  },
  {
    cityCode: 23682,
    cityName: "SAN JOSE DE URE",
    codigo_departamento: 23,
  },
  {
    cityCode: 23686,
    cityName: "SAN PELAYO",
    codigo_departamento: 23,
  },
  { cityCode: 23807, cityName: "TIERRALTA", codigo_departamento: 23 },
  { cityCode: 23815, cityName: "TUCHIN", codigo_departamento: 23 },
  { cityCode: 23855, cityName: "VALENCIA", codigo_departamento: 23 },
  {
    cityCode: 25001,
    cityName: "AGUA DE DIOS",
    codigo_departamento: 25,
  },
  { cityCode: 25019, cityName: "ALBAN", codigo_departamento: 25 },
  { cityCode: 25035, cityName: "ANAPOIMA", codigo_departamento: 25 },
  { cityCode: 25040, cityName: "ANOLAIMA", codigo_departamento: 25 },
  { cityCode: 25053, cityName: "ARBELAEZ", codigo_departamento: 25 },
  { cityCode: 25086, cityName: "BELTRAN", codigo_departamento: 25 },
  { cityCode: 25095, cityName: "BITUIMA", codigo_departamento: 25 },
  { cityCode: 25099, cityName: "BOJACA", codigo_departamento: 25 },
  { cityCode: 25120, cityName: "CABRERA", codigo_departamento: 25 },
  { cityCode: 25123, cityName: "CACHIPAY", codigo_departamento: 25 },
  { cityCode: 25126, cityName: "CAJICA", codigo_departamento: 25 },
  { cityCode: 25148, cityName: "CAPARRAPI", codigo_departamento: 25 },
  { cityCode: 25151, cityName: "CAQUEZA", codigo_departamento: 25 },
  {
    cityCode: 25154,
    cityName: "CARMEN DE CARUPA",
    codigo_departamento: 25,
  },
  { cityCode: 25168, cityName: "CHAGUANI", codigo_departamento: 25 },
  { cityCode: 25175, cityName: "CHIA", codigo_departamento: 25 },
  { cityCode: 25178, cityName: "CHIPAQUE", codigo_departamento: 25 },
  { cityCode: 25181, cityName: "CHOACHI", codigo_departamento: 25 },
  { cityCode: 25183, cityName: "CHOCONTA", codigo_departamento: 25 },
  { cityCode: 25200, cityName: "COGUA", codigo_departamento: 25 },
  { cityCode: 25214, cityName: "COTA", codigo_departamento: 25 },
  { cityCode: 25224, cityName: "CUCUNUBA", codigo_departamento: 25 },
  {
    cityCode: 25245,
    cityName: "EL COLEGIO",
    codigo_departamento: 25,
  },
  { cityCode: 25258, cityName: "EL PEÑON", codigo_departamento: 25 },
  { cityCode: 25260, cityName: "EL ROSAL", codigo_departamento: 25 },
  {
    cityCode: 25269,
    cityName: "FACATATIVA",
    codigo_departamento: 25,
  },
  { cityCode: 25279, cityName: "FOMEQUE", codigo_departamento: 25 },
  { cityCode: 25281, cityName: "FOSCA", codigo_departamento: 25 },
  { cityCode: 25286, cityName: "FUNZA", codigo_departamento: 25 },
  { cityCode: 25288, cityName: "FUQUENE", codigo_departamento: 25 },
  {
    cityCode: 25290,
    cityName: "FUSAGASUGA",
    codigo_departamento: 25,
  },
  { cityCode: 25293, cityName: "GACHALA", codigo_departamento: 25 },
  {
    cityCode: 25295,
    cityName: "GACHANCIPA",
    codigo_departamento: 25,
  },
  { cityCode: 25297, cityName: "GACHETA", codigo_departamento: 25 },
  { cityCode: 25299, cityName: "GAMA", codigo_departamento: 25 },
  { cityCode: 25307, cityName: "GIRARDOT", codigo_departamento: 25 },
  { cityCode: 25312, cityName: "GRANADA", codigo_departamento: 25 },
  { cityCode: 25317, cityName: "GUACHETA", codigo_departamento: 25 },
  { cityCode: 25320, cityName: "GUADUAS", codigo_departamento: 25 },
  { cityCode: 25322, cityName: "GUASCA", codigo_departamento: 25 },
  { cityCode: 25324, cityName: "GUATAQUI", codigo_departamento: 25 },
  { cityCode: 25326, cityName: "GUATAVITA", codigo_departamento: 25 },
  {
    cityCode: 25328,
    cityName: "GUAYABAL DE SIQUIMA",
    codigo_departamento: 25,
  },
  {
    cityCode: 25335,
    cityName: "GUAYABETAL",
    codigo_departamento: 25,
  },
  { cityCode: 25339, cityName: "GUTIERREZ", codigo_departamento: 25 },
  { cityCode: 25368, cityName: "JERUSALEN", codigo_departamento: 25 },
  { cityCode: 25372, cityName: "JUNIN", codigo_departamento: 25 },
  { cityCode: 25377, cityName: "LA CALERA", codigo_departamento: 25 },
  { cityCode: 25386, cityName: "LA MESA", codigo_departamento: 25 },
  { cityCode: 25394, cityName: "LA PALMA", codigo_departamento: 25 },
  { cityCode: 25398, cityName: "LA PEÑA", codigo_departamento: 25 },
  { cityCode: 25402, cityName: "LA VEGA", codigo_departamento: 25 },
  {
    cityCode: 25407,
    cityName: "LENGUAZAQUE",
    codigo_departamento: 25,
  },
  { cityCode: 25426, cityName: "MACHETA", codigo_departamento: 25 },
  { cityCode: 25430, cityName: "MADRID", codigo_departamento: 25 },
  { cityCode: 25436, cityName: "MANTA", codigo_departamento: 25 },
  { cityCode: 25438, cityName: "MEDINA", codigo_departamento: 25 },
  { cityCode: 25473, cityName: "MOSQUERA", codigo_departamento: 25 },
  { cityCode: 25483, cityName: "NARIÑO", codigo_departamento: 25 },
  { cityCode: 25486, cityName: "NEMOCON", codigo_departamento: 25 },
  { cityCode: 25488, cityName: "NILO", codigo_departamento: 25 },
  { cityCode: 25489, cityName: "NIMAIMA", codigo_departamento: 25 },
  { cityCode: 25491, cityName: "NOCAIMA", codigo_departamento: 25 },
  { cityCode: 25506, cityName: "VENECIA", codigo_departamento: 25 },
  { cityCode: 25513, cityName: "PACHO", codigo_departamento: 25 },
  { cityCode: 25518, cityName: "PAIME", codigo_departamento: 25 },
  { cityCode: 25524, cityName: "PANDI", codigo_departamento: 25 },
  {
    cityCode: 25530,
    cityName: "PARATEBUENO",
    codigo_departamento: 25,
  },
  { cityCode: 25535, cityName: "PASCA", codigo_departamento: 25 },
  {
    cityCode: 25572,
    cityName: "PUERTO SALGAR",
    codigo_departamento: 25,
  },
  { cityCode: 25580, cityName: "PULI", codigo_departamento: 25 },
  {
    cityCode: 25592,
    cityName: "QUEBRADANEGRA",
    codigo_departamento: 25,
  },
  { cityCode: 25594, cityName: "QUETAME", codigo_departamento: 25 },
  { cityCode: 25596, cityName: "QUIPILE", codigo_departamento: 25 },
  { cityCode: 25599, cityName: "APULO", codigo_departamento: 25 },
  { cityCode: 25612, cityName: "RICAURTE", codigo_departamento: 25 },
  {
    cityCode: 25645,
    cityName: "SAN ANTONIO DEL TEQUENDAMA",
    codigo_departamento: 25,
  },
  {
    cityCode: 25649,
    cityName: "SAN BERNARDO",
    codigo_departamento: 25,
  },
  {
    cityCode: 25653,
    cityName: "SAN CAYETANO",
    codigo_departamento: 25,
  },
  {
    cityCode: 25658,
    cityName: "SAN FRANCISCO",
    codigo_departamento: 25,
  },
  {
    cityCode: 25662,
    cityName: "SAN JUAN DE RIOSECO",
    codigo_departamento: 25,
  },
  { cityCode: 25718, cityName: "SASAIMA", codigo_departamento: 25 },
  { cityCode: 25736, cityName: "SESQUILE", codigo_departamento: 25 },
  { cityCode: 25740, cityName: "SIBATE", codigo_departamento: 25 },
  { cityCode: 25743, cityName: "SILVANIA", codigo_departamento: 25 },
  { cityCode: 25745, cityName: "SIMIJACA", codigo_departamento: 25 },
  { cityCode: 25754, cityName: "SOACHA", codigo_departamento: 25 },
  { cityCode: 25758, cityName: "SOPO", codigo_departamento: 25 },
  {
    cityCode: 25769,
    cityName: "SUBACHOQUE",
    codigo_departamento: 25,
  },
  { cityCode: 25772, cityName: "SUESCA", codigo_departamento: 25 },
  { cityCode: 25777, cityName: "SUPATA", codigo_departamento: 25 },
  { cityCode: 25779, cityName: "SUSA", codigo_departamento: 25 },
  { cityCode: 25781, cityName: "SUTATAUSA", codigo_departamento: 25 },
  { cityCode: 25785, cityName: "TABIO", codigo_departamento: 25 },
  { cityCode: 25793, cityName: "TAUSA", codigo_departamento: 25 },
  { cityCode: 25797, cityName: "TENA", codigo_departamento: 25 },
  { cityCode: 25799, cityName: "TENJO", codigo_departamento: 25 },
  { cityCode: 25805, cityName: "TIBACUY", codigo_departamento: 25 },
  { cityCode: 25807, cityName: "TIBIRITA", codigo_departamento: 25 },
  { cityCode: 25815, cityName: "TOCAIMA", codigo_departamento: 25 },
  { cityCode: 25817, cityName: "TOCANCIPA", codigo_departamento: 25 },
  { cityCode: 25823, cityName: "TOPAIPI", codigo_departamento: 25 },
  { cityCode: 25839, cityName: "UBALA", codigo_departamento: 25 },
  { cityCode: 25841, cityName: "UBAQUE", codigo_departamento: 25 },
  {
    cityCode: 25843,
    cityName: "VILLA DE SAN DIEGO DE UBATE",
    codigo_departamento: 25,
  },
  { cityCode: 25845, cityName: "UNE", codigo_departamento: 25 },
  { cityCode: 25851, cityName: "UTICA", codigo_departamento: 25 },
  { cityCode: 25862, cityName: "VERGARA", codigo_departamento: 25 },
  { cityCode: 25867, cityName: "VIANI", codigo_departamento: 25 },
  {
    cityCode: 25871,
    cityName: "VILLAGOMEZ",
    codigo_departamento: 25,
  },
  {
    cityCode: 25873,
    cityName: "VILLAPINZON",
    codigo_departamento: 25,
  },
  { cityCode: 25875, cityName: "VILLETA", codigo_departamento: 25 },
  { cityCode: 25878, cityName: "VIOTA", codigo_departamento: 25 },
  { cityCode: 25885, cityName: "YACOPI", codigo_departamento: 25 },
  { cityCode: 25898, cityName: "ZIPACON", codigo_departamento: 25 },
  { cityCode: 25899, cityName: "ZIPAQUIRA", codigo_departamento: 25 },
  { cityCode: 27001, cityName: "QUIBDO", codigo_departamento: 27 },
  { cityCode: 27006, cityName: "ACANDI", codigo_departamento: 27 },
  {
    cityCode: 27025,
    cityName: "ALTO BAUDO",
    codigo_departamento: 27,
  },
  { cityCode: 27050, cityName: "ATRATO", codigo_departamento: 27 },
  { cityCode: 27073, cityName: "BAGADO", codigo_departamento: 27 },
  {
    cityCode: 27075,
    cityName: "BAHIA SOLANO",
    codigo_departamento: 27,
  },
  {
    cityCode: 27077,
    cityName: "BAJO BAUDO",
    codigo_departamento: 27,
  },
  { cityCode: 27099, cityName: "BOJAYA", codigo_departamento: 27 },
  {
    cityCode: 27135,
    cityName: "EL CANTON DEL SAN PABLO",
    codigo_departamento: 27,
  },
  {
    cityCode: 27150,
    cityName: "CARMEN DEL DARIEN",
    codigo_departamento: 27,
  },
  { cityCode: 27160, cityName: "CERTEGUI", codigo_departamento: 27 },
  { cityCode: 27205, cityName: "CONDOTO", codigo_departamento: 27 },
  {
    cityCode: 27245,
    cityName: "EL CARMEN DE ATRATO",
    codigo_departamento: 27,
  },
  {
    cityCode: 27250,
    cityName: "EL LITORAL DEL SAN JUAN",
    codigo_departamento: 27,
  },
  { cityCode: 27361, cityName: "ISTMINA", codigo_departamento: 27 },
  { cityCode: 27372, cityName: "JURADO", codigo_departamento: 27 },
  { cityCode: 27413, cityName: "LLORO", codigo_departamento: 27 },
  {
    cityCode: 27425,
    cityName: "MEDIO ATRATO",
    codigo_departamento: 27,
  },
  {
    cityCode: 27430,
    cityName: "MEDIO BAUDO",
    codigo_departamento: 27,
  },
  {
    cityCode: 27450,
    cityName: "MEDIO SAN JUAN",
    codigo_departamento: 27,
  },
  { cityCode: 27491, cityName: "NOVITA", codigo_departamento: 27 },
  { cityCode: 27495, cityName: "NUQUI", codigo_departamento: 27 },
  { cityCode: 27580, cityName: "RIO IRO", codigo_departamento: 27 },
  { cityCode: 27600, cityName: "RIO QUITO", codigo_departamento: 27 },
  { cityCode: 27615, cityName: "RIOSUCIO", codigo_departamento: 27 },
  {
    cityCode: 27660,
    cityName: "SAN JOSE DEL PALMAR",
    codigo_departamento: 27,
  },
  { cityCode: 27745, cityName: "SIPI", codigo_departamento: 27 },
  { cityCode: 27787, cityName: "TADO", codigo_departamento: 27 },
  { cityCode: 27800, cityName: "UNGUIA", codigo_departamento: 27 },
  {
    cityCode: 27810,
    cityName: "UNION PANAMERICANA",
    codigo_departamento: 27,
  },
  { cityCode: 41001, cityName: "NEIVA", codigo_departamento: 41 },
  { cityCode: 41006, cityName: "ACEVEDO", codigo_departamento: 41 },
  { cityCode: 41013, cityName: "AGRADO", codigo_departamento: 41 },
  { cityCode: 41016, cityName: "AIPE", codigo_departamento: 41 },
  { cityCode: 41020, cityName: "ALGECIRAS", codigo_departamento: 41 },
  { cityCode: 41026, cityName: "ALTAMIRA", codigo_departamento: 41 },
  { cityCode: 41078, cityName: "BARAYA", codigo_departamento: 41 },
  {
    cityCode: 41132,
    cityName: "CAMPOALEGRE",
    codigo_departamento: 41,
  },
  { cityCode: 41206, cityName: "COLOMBIA", codigo_departamento: 41 },
  { cityCode: 41244, cityName: "ELIAS", codigo_departamento: 41 },
  { cityCode: 41298, cityName: "GARZON", codigo_departamento: 41 },
  { cityCode: 41306, cityName: "GIGANTE", codigo_departamento: 41 },
  { cityCode: 41319, cityName: "GUADALUPE", codigo_departamento: 41 },
  { cityCode: 41349, cityName: "HOBO", codigo_departamento: 41 },
  { cityCode: 41357, cityName: "IQUIRA", codigo_departamento: 41 },
  { cityCode: 41359, cityName: "ISNOS", codigo_departamento: 41 },
  {
    cityCode: 41378,
    cityName: "LA ARGENTINA",
    codigo_departamento: 41,
  },
  { cityCode: 41396, cityName: "LA PLATA", codigo_departamento: 41 },
  { cityCode: 41483, cityName: "NATAGA", codigo_departamento: 41 },
  { cityCode: 41503, cityName: "OPORAPA", codigo_departamento: 41 },
  { cityCode: 41518, cityName: "PAICOL", codigo_departamento: 41 },
  { cityCode: 41524, cityName: "PALERMO", codigo_departamento: 41 },
  { cityCode: 41530, cityName: "PALESTINA", codigo_departamento: 41 },
  { cityCode: 41548, cityName: "PITAL", codigo_departamento: 41 },
  { cityCode: 41551, cityName: "PITALITO", codigo_departamento: 41 },
  { cityCode: 41615, cityName: "RIVERA", codigo_departamento: 41 },
  {
    cityCode: 41660,
    cityName: "SALADOBLANCO",
    codigo_departamento: 41,
  },
  {
    cityCode: 41668,
    cityName: "SAN AGUSTIN",
    codigo_departamento: 41,
  },
  {
    cityCode: 41676,
    cityName: "SANTA MARIA",
    codigo_departamento: 41,
  },
  { cityCode: 41770, cityName: "SUAZA", codigo_departamento: 41 },
  { cityCode: 41791, cityName: "TARQUI", codigo_departamento: 41 },
  { cityCode: 41797, cityName: "TESALIA", codigo_departamento: 41 },
  { cityCode: 41799, cityName: "TELLO", codigo_departamento: 41 },
  { cityCode: 41801, cityName: "TERUEL", codigo_departamento: 41 },
  { cityCode: 41807, cityName: "TIMANA", codigo_departamento: 41 },
  {
    cityCode: 41872,
    cityName: "VILLAVIEJA",
    codigo_departamento: 41,
  },
  { cityCode: 41885, cityName: "YAGUARA", codigo_departamento: 41 },
  { cityCode: 44001, cityName: "RIOHACHA", codigo_departamento: 44 },
  { cityCode: 44035, cityName: "ALBANIA", codigo_departamento: 44 },
  { cityCode: 44078, cityName: "BARRANCAS", codigo_departamento: 44 },
  { cityCode: 44090, cityName: "DIBULLA", codigo_departamento: 44 },
  {
    cityCode: 44098,
    cityName: "DISTRACCION",
    codigo_departamento: 44,
  },
  { cityCode: 44110, cityName: "EL MOLINO", codigo_departamento: 44 },
  { cityCode: 44279, cityName: "FONSECA", codigo_departamento: 44 },
  { cityCode: 44378, cityName: "HATONUEVO", codigo_departamento: 44 },
  {
    cityCode: 44420,
    cityName: "LA JAGUA DEL PILAR",
    codigo_departamento: 44,
  },
  { cityCode: 44430, cityName: "MAICAO", codigo_departamento: 44 },
  { cityCode: 44560, cityName: "MANAURE", codigo_departamento: 44 },
  {
    cityCode: 44650,
    cityName: "SAN JUAN DEL CESAR",
    codigo_departamento: 44,
  },
  { cityCode: 44847, cityName: "URIBIA", codigo_departamento: 44 },
  { cityCode: 44855, cityName: "URUMITA", codigo_departamento: 44 },
  {
    cityCode: 44874,
    cityName: "VILLANUEVA",
    codigo_departamento: 44,
  },
  {
    cityCode: 47001,
    cityName: "SANTA MARTA",
    codigo_departamento: 47,
  },
  { cityCode: 47030, cityName: "ALGARROBO", codigo_departamento: 47 },
  { cityCode: 47053, cityName: "ARACATACA", codigo_departamento: 47 },
  { cityCode: 47058, cityName: "ARIGUANI", codigo_departamento: 47 },
  {
    cityCode: 47161,
    cityName: "CERRO DE SAN ANTONIO",
    codigo_departamento: 47,
  },
  { cityCode: 47170, cityName: "CHIVOLO", codigo_departamento: 47 },
  { cityCode: 47189, cityName: "CIENAGA", codigo_departamento: 47 },
  { cityCode: 47205, cityName: "CONCORDIA", codigo_departamento: 47 },
  { cityCode: 47245, cityName: "EL BANCO", codigo_departamento: 47 },
  { cityCode: 47258, cityName: "EL PIÑON", codigo_departamento: 47 },
  { cityCode: 47268, cityName: "EL RETEN", codigo_departamento: 47 },
  { cityCode: 47288, cityName: "FUNDACION", codigo_departamento: 47 },
  { cityCode: 47318, cityName: "GUAMAL", codigo_departamento: 47 },
  {
    cityCode: 47460,
    cityName: "NUEVA GRANADA",
    codigo_departamento: 47,
  },
  { cityCode: 47541, cityName: "PEDRAZA", codigo_departamento: 47 },
  {
    cityCode: 47545,
    cityName: "PIJIÑO DEL CARMEN",
    codigo_departamento: 47,
  },
  { cityCode: 47551, cityName: "PIVIJAY", codigo_departamento: 47 },
  { cityCode: 47555, cityName: "PLATO", codigo_departamento: 47 },
  {
    cityCode: 47570,
    cityName: "PUEBLOVIEJO",
    codigo_departamento: 47,
  },
  { cityCode: 47605, cityName: "REMOLINO", codigo_departamento: 47 },
  {
    cityCode: 47660,
    cityName: "SABANAS DE SAN ANGEL",
    codigo_departamento: 47,
  },
  { cityCode: 47675, cityName: "SALAMINA", codigo_departamento: 47 },
  {
    cityCode: 47692,
    cityName: "SAN SEBASTIAN DE BUENAVISTA",
    codigo_departamento: 47,
  },
  { cityCode: 47703, cityName: "SAN ZENON", codigo_departamento: 47 },
  { cityCode: 47707, cityName: "SANTA ANA", codigo_departamento: 47 },
  {
    cityCode: 47720,
    cityName: "SANTA BARBARA DE PINTO",
    codigo_departamento: 47,
  },
  {
    cityCode: 47745,
    cityName: "SITIONUEVO",
    codigo_departamento: 47,
  },
  { cityCode: 47798, cityName: "TENERIFE", codigo_departamento: 47 },
  { cityCode: 47960, cityName: "ZAPAYAN", codigo_departamento: 47 },
  {
    cityCode: 47980,
    cityName: "ZONA BANANERA",
    codigo_departamento: 47,
  },
  {
    cityCode: 50001,
    cityName: "VILLAVICENCIO",
    codigo_departamento: 50,
  },
  { cityCode: 50006, cityName: "ACACIAS", codigo_departamento: 50 },
  {
    cityCode: 50110,
    cityName: "BARRANCA DE UPIA",
    codigo_departamento: 50,
  },
  { cityCode: 50124, cityName: "CABUYARO", codigo_departamento: 50 },
  {
    cityCode: 50150,
    cityName: "CASTILLA LA NUEVA",
    codigo_departamento: 50,
  },
  { cityCode: 50223, cityName: "CUBARRAL", codigo_departamento: 50 },
  { cityCode: 50226, cityName: "CUMARAL", codigo_departamento: 50 },
  {
    cityCode: 50245,
    cityName: "EL CALVARIO",
    codigo_departamento: 50,
  },
  {
    cityCode: 50251,
    cityName: "EL CASTILLO",
    codigo_departamento: 50,
  },
  { cityCode: 50270, cityName: "EL DORADO", codigo_departamento: 50 },
  {
    cityCode: 50287,
    cityName: "FUENTE DE ORO",
    codigo_departamento: 50,
  },
  { cityCode: 50313, cityName: "GRANADA", codigo_departamento: 50 },
  { cityCode: 50318, cityName: "GUAMAL", codigo_departamento: 50 },
  { cityCode: 50325, cityName: "MAPIRIPAN", codigo_departamento: 50 },
  { cityCode: 50330, cityName: "MESETAS", codigo_departamento: 50 },
  {
    cityCode: 50350,
    cityName: "LA MACARENA",
    codigo_departamento: 50,
  },
  { cityCode: 50370, cityName: "URIBE", codigo_departamento: 50 },
  { cityCode: 50400, cityName: "LEJANIAS", codigo_departamento: 50 },
  {
    cityCode: 50450,
    cityName: "PUERTO CONCORDIA",
    codigo_departamento: 50,
  },
  {
    cityCode: 50568,
    cityName: "PUERTO GAITAN",
    codigo_departamento: 50,
  },
  {
    cityCode: 50573,
    cityName: "PUERTO LOPEZ",
    codigo_departamento: 50,
  },
  {
    cityCode: 50577,
    cityName: "PUERTO LLERAS",
    codigo_departamento: 50,
  },
  {
    cityCode: 50590,
    cityName: "PUERTO RICO",
    codigo_departamento: 50,
  },
  { cityCode: 50606, cityName: "RESTREPO", codigo_departamento: 50 },
  {
    cityCode: 50680,
    cityName: "SAN CARLOS DE GUAROA",
    codigo_departamento: 50,
  },
  {
    cityCode: 50683,
    cityName: "SAN JUAN DE ARAMA",
    codigo_departamento: 50,
  },
  {
    cityCode: 50686,
    cityName: "SAN JUANITO",
    codigo_departamento: 50,
  },
  {
    cityCode: 50689,
    cityName: "SAN MARTIN",
    codigo_departamento: 50,
  },
  {
    cityCode: 50711,
    cityName: "VISTAHERMOSA",
    codigo_departamento: 50,
  },
  { cityCode: 52001, cityName: "PASTO", codigo_departamento: 52 },
  { cityCode: 52019, cityName: "ALBAN", codigo_departamento: 52 },
  { cityCode: 52022, cityName: "ALDANA", codigo_departamento: 52 },
  { cityCode: 52036, cityName: "ANCUYA", codigo_departamento: 52 },
  { cityCode: 52051, cityName: "ARBOLEDA", codigo_departamento: 52 },
  { cityCode: 52079, cityName: "BARBACOAS", codigo_departamento: 52 },
  { cityCode: 52083, cityName: "BELEN", codigo_departamento: 52 },
  { cityCode: 52110, cityName: "BUESACO", codigo_departamento: 52 },
  { cityCode: 52203, cityName: "COLON", codigo_departamento: 52 },
  { cityCode: 52207, cityName: "CONSACA", codigo_departamento: 52 },
  { cityCode: 52210, cityName: "CONTADERO", codigo_departamento: 52 },
  { cityCode: 52215, cityName: "CORDOBA", codigo_departamento: 52 },
  {
    cityCode: 52224,
    cityName: "CUASPUD CARLOSAMA",
    codigo_departamento: 52,
  },
  { cityCode: 52227, cityName: "CUMBAL", codigo_departamento: 52 },
  { cityCode: 52233, cityName: "CUMBITARA", codigo_departamento: 52 },
  { cityCode: 52240, cityName: "CHACHAGÜI", codigo_departamento: 52 },
  { cityCode: 52250, cityName: "EL CHARCO", codigo_departamento: 52 },
  { cityCode: 52254, cityName: "EL PEÑOL", codigo_departamento: 52 },
  {
    cityCode: 52256,
    cityName: "EL ROSARIO",
    codigo_departamento: 52,
  },
  {
    cityCode: 52258,
    cityName: "EL TABLON DE GOMEZ",
    codigo_departamento: 52,
  },
  { cityCode: 52260, cityName: "EL TAMBO", codigo_departamento: 52 },
  { cityCode: 52287, cityName: "FUNES", codigo_departamento: 52 },
  { cityCode: 52317, cityName: "GUACHUCAL", codigo_departamento: 52 },
  {
    cityCode: 52320,
    cityName: "GUAITARILLA",
    codigo_departamento: 52,
  },
  { cityCode: 52323, cityName: "GUALMATAN", codigo_departamento: 52 },
  { cityCode: 52352, cityName: "ILES", codigo_departamento: 52 },
  { cityCode: 52354, cityName: "IMUES", codigo_departamento: 52 },
  { cityCode: 52356, cityName: "IPIALES", codigo_departamento: 52 },
  { cityCode: 52378, cityName: "LA CRUZ", codigo_departamento: 52 },
  {
    cityCode: 52381,
    cityName: "LA FLORIDA",
    codigo_departamento: 52,
  },
  {
    cityCode: 52385,
    cityName: "LA LLANADA",
    codigo_departamento: 52,
  },
  { cityCode: 52390, cityName: "LA TOLA", codigo_departamento: 52 },
  { cityCode: 52399, cityName: "LA UNION", codigo_departamento: 52 },
  { cityCode: 52405, cityName: "LEIVA", codigo_departamento: 52 },
  { cityCode: 52411, cityName: "LINARES", codigo_departamento: 52 },
  { cityCode: 52418, cityName: "LOS ANDES", codigo_departamento: 52 },
  { cityCode: 52427, cityName: "MAGÜI", codigo_departamento: 52 },
  { cityCode: 52435, cityName: "MALLAMA", codigo_departamento: 52 },
  { cityCode: 52473, cityName: "MOSQUERA", codigo_departamento: 52 },
  { cityCode: 52480, cityName: "NARIÑO", codigo_departamento: 52 },
  {
    cityCode: 52490,
    cityName: "OLAYA HERRERA",
    codigo_departamento: 52,
  },
  { cityCode: 52506, cityName: "OSPINA", codigo_departamento: 52 },
  {
    cityCode: 52520,
    cityName: "FRANCISCO PIZARRO",
    codigo_departamento: 52,
  },
  { cityCode: 52540, cityName: "POLICARPA", codigo_departamento: 52 },
  { cityCode: 52560, cityName: "POTOSI", codigo_departamento: 52 },
  {
    cityCode: 52565,
    cityName: "PROVIDENCIA",
    codigo_departamento: 52,
  },
  { cityCode: 52573, cityName: "PUERRES", codigo_departamento: 52 },
  { cityCode: 52585, cityName: "PUPIALES", codigo_departamento: 52 },
  { cityCode: 52612, cityName: "RICAURTE", codigo_departamento: 52 },
  {
    cityCode: 52621,
    cityName: "ROBERTO PAYAN",
    codigo_departamento: 52,
  },
  { cityCode: 52678, cityName: "SAMANIEGO", codigo_departamento: 52 },
  { cityCode: 52683, cityName: "SANDONA", codigo_departamento: 52 },
  {
    cityCode: 52685,
    cityName: "SAN BERNARDO",
    codigo_departamento: 52,
  },
  {
    cityCode: 52687,
    cityName: "SAN LORENZO",
    codigo_departamento: 52,
  },
  { cityCode: 52693, cityName: "SAN PABLO", codigo_departamento: 52 },
  {
    cityCode: 52694,
    cityName: "SAN PEDRO DE CARTAGO",
    codigo_departamento: 52,
  },
  {
    cityCode: 52696,
    cityName: "SANTA BARBARA",
    codigo_departamento: 52,
  },
  { cityCode: 52699, cityName: "SANTACRUZ", codigo_departamento: 52 },
  { cityCode: 52720, cityName: "SAPUYES", codigo_departamento: 52 },
  { cityCode: 52786, cityName: "TAMINANGO", codigo_departamento: 52 },
  { cityCode: 52788, cityName: "TANGUA", codigo_departamento: 52 },
  {
    cityCode: 52835,
    cityName: "SAN ANDRES DE TUMACO",
    codigo_departamento: 52,
  },
  { cityCode: 52838, cityName: "TUQUERRES", codigo_departamento: 52 },
  {
    cityCode: 52885,
    cityName: "YACUANQUER",
    codigo_departamento: 52,
  },
  {
    cityCode: 54001,
    cityName: "SAN JOSE DE CUCUTA",
    codigo_departamento: 54,
  },
  { cityCode: 54003, cityName: "ABREGO", codigo_departamento: 54 },
  { cityCode: 54051, cityName: "ARBOLEDAS", codigo_departamento: 54 },
  { cityCode: 54099, cityName: "BOCHALEMA", codigo_departamento: 54 },
  {
    cityCode: 54109,
    cityName: "BUCARASICA",
    codigo_departamento: 54,
  },
  { cityCode: 54125, cityName: "CACOTA", codigo_departamento: 54 },
  { cityCode: 54128, cityName: "CACHIRA", codigo_departamento: 54 },
  { cityCode: 54172, cityName: "CHINACOTA", codigo_departamento: 54 },
  { cityCode: 54174, cityName: "CHITAGA", codigo_departamento: 54 },
  {
    cityCode: 54206,
    cityName: "CONVENCION",
    codigo_departamento: 54,
  },
  { cityCode: 54223, cityName: "CUCUTILLA", codigo_departamento: 54 },
  { cityCode: 54239, cityName: "DURANIA", codigo_departamento: 54 },
  { cityCode: 54245, cityName: "EL CARMEN", codigo_departamento: 54 },
  { cityCode: 54250, cityName: "EL TARRA", codigo_departamento: 54 },
  { cityCode: 54261, cityName: "EL ZULIA", codigo_departamento: 54 },
  { cityCode: 54313, cityName: "GRAMALOTE", codigo_departamento: 54 },
  { cityCode: 54344, cityName: "HACARI", codigo_departamento: 54 },
  { cityCode: 54347, cityName: "HERRAN", codigo_departamento: 54 },
  { cityCode: 54377, cityName: "LABATECA", codigo_departamento: 54 },
  {
    cityCode: 54385,
    cityName: "LA ESPERANZA",
    codigo_departamento: 54,
  },
  { cityCode: 54398, cityName: "LA PLAYA", codigo_departamento: 54 },
  {
    cityCode: 54405,
    cityName: "LOS PATIOS",
    codigo_departamento: 54,
  },
  { cityCode: 54418, cityName: "LOURDES", codigo_departamento: 54 },
  { cityCode: 54480, cityName: "MUTISCUA", codigo_departamento: 54 },
  { cityCode: 54498, cityName: "OCAÑA", codigo_departamento: 54 },
  { cityCode: 54518, cityName: "PAMPLONA", codigo_departamento: 54 },
  {
    cityCode: 54520,
    cityName: "PAMPLONITA",
    codigo_departamento: 54,
  },
  {
    cityCode: 54553,
    cityName: "PUERTO SANTANDER",
    codigo_departamento: 54,
  },
  {
    cityCode: 54599,
    cityName: "RAGONVALIA",
    codigo_departamento: 54,
  },
  { cityCode: 54660, cityName: "SALAZAR", codigo_departamento: 54 },
  {
    cityCode: 54670,
    cityName: "SAN CALIXTO",
    codigo_departamento: 54,
  },
  {
    cityCode: 54673,
    cityName: "SAN CAYETANO",
    codigo_departamento: 54,
  },
  { cityCode: 54680, cityName: "SANTIAGO", codigo_departamento: 54 },
  { cityCode: 54720, cityName: "SARDINATA", codigo_departamento: 54 },
  { cityCode: 54743, cityName: "SILOS", codigo_departamento: 54 },
  { cityCode: 54800, cityName: "TEORAMA", codigo_departamento: 54 },
  { cityCode: 54810, cityName: "TIBU", codigo_departamento: 54 },
  { cityCode: 54820, cityName: "TOLEDO", codigo_departamento: 54 },
  {
    cityCode: 54871,
    cityName: "VILLA CARO",
    codigo_departamento: 54,
  },
  {
    cityCode: 54874,
    cityName: "VILLA DEL ROSARIO",
    codigo_departamento: 54,
  },
  { cityCode: 63001, cityName: "ARMENIA", codigo_departamento: 63 },
  {
    cityCode: 63111,
    cityName: "BUENAVISTA",
    codigo_departamento: 63,
  },
  { cityCode: 63130, cityName: "CALARCA", codigo_departamento: 63 },
  { cityCode: 63190, cityName: "CIRCASIA", codigo_departamento: 63 },
  { cityCode: 63212, cityName: "CORDOBA", codigo_departamento: 63 },
  { cityCode: 63272, cityName: "FILANDIA", codigo_departamento: 63 },
  { cityCode: 63302, cityName: "GENOVA", codigo_departamento: 63 },
  {
    cityCode: 63401,
    cityName: "LA TEBAIDA",
    codigo_departamento: 63,
  },
  {
    cityCode: 63470,
    cityName: "MONTENEGRO",
    codigo_departamento: 63,
  },
  { cityCode: 63548, cityName: "PIJAO", codigo_departamento: 63 },
  { cityCode: 63594, cityName: "QUIMBAYA", codigo_departamento: 63 },
  { cityCode: 63690, cityName: "SALENTO", codigo_departamento: 63 },
  { cityCode: 66001, cityName: "PEREIRA", codigo_departamento: 66 },
  { cityCode: 66045, cityName: "APIA", codigo_departamento: 66 },
  { cityCode: 66075, cityName: "BALBOA", codigo_departamento: 66 },
  {
    cityCode: 66088,
    cityName: "BELEN DE UMBRIA",
    codigo_departamento: 66,
  },
  {
    cityCode: 66170,
    cityName: "DOSQUEBRADAS",
    codigo_departamento: 66,
  },
  { cityCode: 66318, cityName: "GUATICA", codigo_departamento: 66 },
  { cityCode: 66383, cityName: "LA CELIA", codigo_departamento: 66 },
  {
    cityCode: 66400,
    cityName: "LA VIRGINIA",
    codigo_departamento: 66,
  },
  { cityCode: 66440, cityName: "MARSELLA", codigo_departamento: 66 },
  { cityCode: 66456, cityName: "MISTRATO", codigo_departamento: 66 },
  {
    cityCode: 66572,
    cityName: "PUEBLO RICO",
    codigo_departamento: 66,
  },
  { cityCode: 66594, cityName: "QUINCHIA", codigo_departamento: 66 },
  {
    cityCode: 66682,
    cityName: "SANTA ROSA DE CABAL",
    codigo_departamento: 66,
  },
  { cityCode: 66687, cityName: "SANTUARIO", codigo_departamento: 66 },
  {
    cityCode: 68001,
    cityName: "BUCARAMANGA",
    codigo_departamento: 68,
  },
  { cityCode: 68013, cityName: "AGUADA", codigo_departamento: 68 },
  { cityCode: 68020, cityName: "ALBANIA", codigo_departamento: 68 },
  { cityCode: 68051, cityName: "ARATOCA", codigo_departamento: 68 },
  { cityCode: 68077, cityName: "BARBOSA", codigo_departamento: 68 },
  { cityCode: 68079, cityName: "BARICHARA", codigo_departamento: 68 },
  {
    cityCode: 68081,
    cityName: "BARRANCABERMEJA",
    codigo_departamento: 68,
  },
  { cityCode: 68092, cityName: "BETULIA", codigo_departamento: 68 },
  { cityCode: 68101, cityName: "BOLIVAR", codigo_departamento: 68 },
  { cityCode: 68121, cityName: "CABRERA", codigo_departamento: 68 },
  {
    cityCode: 68132,
    cityName: "CALIFORNIA",
    codigo_departamento: 68,
  },
  {
    cityCode: 68147,
    cityName: "CAPITANEJO",
    codigo_departamento: 68,
  },
  { cityCode: 68152, cityName: "CARCASI", codigo_departamento: 68 },
  { cityCode: 68160, cityName: "CEPITA", codigo_departamento: 68 },
  { cityCode: 68162, cityName: "CERRITO", codigo_departamento: 68 },
  { cityCode: 68167, cityName: "CHARALA", codigo_departamento: 68 },
  { cityCode: 68169, cityName: "CHARTA", codigo_departamento: 68 },
  { cityCode: 68176, cityName: "CHIMA", codigo_departamento: 68 },
  { cityCode: 68179, cityName: "CHIPATA", codigo_departamento: 68 },
  { cityCode: 68190, cityName: "CIMITARRA", codigo_departamento: 68 },
  {
    cityCode: 68207,
    cityName: "CONCEPCION",
    codigo_departamento: 68,
  },
  { cityCode: 68209, cityName: "CONFINES", codigo_departamento: 68 },
  {
    cityCode: 68211,
    cityName: "CONTRATACION",
    codigo_departamento: 68,
  },
  { cityCode: 68217, cityName: "COROMORO", codigo_departamento: 68 },
  { cityCode: 68229, cityName: "CURITI", codigo_departamento: 68 },
  {
    cityCode: 68235,
    cityName: "EL CARMEN DE CHUCURI",
    codigo_departamento: 68,
  },
  {
    cityCode: 68245,
    cityName: "EL GUACAMAYO",
    codigo_departamento: 68,
  },
  { cityCode: 68250, cityName: "EL PEÑON", codigo_departamento: 68 },
  { cityCode: 68255, cityName: "EL PLAYON", codigo_departamento: 68 },
  { cityCode: 68264, cityName: "ENCINO", codigo_departamento: 68 },
  { cityCode: 68266, cityName: "ENCISO", codigo_departamento: 68 },
  { cityCode: 68271, cityName: "FLORIAN", codigo_departamento: 68 },
  {
    cityCode: 68276,
    cityName: "FLORIDABLANCA",
    codigo_departamento: 68,
  },
  { cityCode: 68296, cityName: "GALAN", codigo_departamento: 68 },
  { cityCode: 68298, cityName: "GAMBITA", codigo_departamento: 68 },
  { cityCode: 68307, cityName: "GIRON", codigo_departamento: 68 },
  { cityCode: 68318, cityName: "GUACA", codigo_departamento: 68 },
  { cityCode: 68320, cityName: "GUADALUPE", codigo_departamento: 68 },
  { cityCode: 68322, cityName: "GUAPOTA", codigo_departamento: 68 },
  { cityCode: 68324, cityName: "GUAVATA", codigo_departamento: 68 },
  { cityCode: 68327, cityName: "GÜEPSA", codigo_departamento: 68 },
  { cityCode: 68344, cityName: "HATO", codigo_departamento: 68 },
  {
    cityCode: 68368,
    cityName: "JESUS MARIA",
    codigo_departamento: 68,
  },
  { cityCode: 68370, cityName: "JORDAN", codigo_departamento: 68 },
  {
    cityCode: 68377,
    cityName: "LA BELLEZA",
    codigo_departamento: 68,
  },
  { cityCode: 68385, cityName: "LANDAZURI", codigo_departamento: 68 },
  { cityCode: 68397, cityName: "LA PAZ", codigo_departamento: 68 },
  { cityCode: 68406, cityName: "LEBRIJA", codigo_departamento: 68 },
  {
    cityCode: 68418,
    cityName: "LOS SANTOS",
    codigo_departamento: 68,
  },
  {
    cityCode: 68425,
    cityName: "MACARAVITA",
    codigo_departamento: 68,
  },
  { cityCode: 68432, cityName: "MALAGA", codigo_departamento: 68 },
  { cityCode: 68444, cityName: "MATANZA", codigo_departamento: 68 },
  { cityCode: 68464, cityName: "MOGOTES", codigo_departamento: 68 },
  {
    cityCode: 68468,
    cityName: "MOLAGAVITA",
    codigo_departamento: 68,
  },
  { cityCode: 68498, cityName: "OCAMONTE", codigo_departamento: 68 },
  { cityCode: 68500, cityName: "OIBA", codigo_departamento: 68 },
  { cityCode: 68502, cityName: "ONZAGA", codigo_departamento: 68 },
  { cityCode: 68522, cityName: "PALMAR", codigo_departamento: 68 },
  {
    cityCode: 68524,
    cityName: "PALMAS DEL SOCORRO",
    codigo_departamento: 68,
  },
  { cityCode: 68533, cityName: "PARAMO", codigo_departamento: 68 },
  {
    cityCode: 68547,
    cityName: "PIEDECUESTA",
    codigo_departamento: 68,
  },
  { cityCode: 68549, cityName: "PINCHOTE", codigo_departamento: 68 },
  {
    cityCode: 68572,
    cityName: "PUENTE NACIONAL",
    codigo_departamento: 68,
  },
  {
    cityCode: 68573,
    cityName: "PUERTO PARRA",
    codigo_departamento: 68,
  },
  {
    cityCode: 68575,
    cityName: "PUERTO WILCHES",
    codigo_departamento: 68,
  },
  { cityCode: 68615, cityName: "RIONEGRO", codigo_departamento: 68 },
  {
    cityCode: 68655,
    cityName: "SABANA DE TORRES",
    codigo_departamento: 68,
  },
  {
    cityCode: 68669,
    cityName: "SAN ANDRES",
    codigo_departamento: 68,
  },
  {
    cityCode: 68673,
    cityName: "SAN BENITO",
    codigo_departamento: 68,
  },
  { cityCode: 68679, cityName: "SAN GIL", codigo_departamento: 68 },
  {
    cityCode: 68682,
    cityName: "SAN JOAQUIN",
    codigo_departamento: 68,
  },
  {
    cityCode: 68684,
    cityName: "SAN JOSE DE MIRANDA",
    codigo_departamento: 68,
  },
  {
    cityCode: 68686,
    cityName: "SAN MIGUEL",
    codigo_departamento: 68,
  },
  {
    cityCode: 68689,
    cityName: "SAN VICENTE DE CHUCURI",
    codigo_departamento: 68,
  },
  {
    cityCode: 68705,
    cityName: "SANTA BARBARA",
    codigo_departamento: 68,
  },
  {
    cityCode: 68720,
    cityName: "SANTA HELENA DEL OPON",
    codigo_departamento: 68,
  },
  { cityCode: 68745, cityName: "SIMACOTA", codigo_departamento: 68 },
  { cityCode: 68755, cityName: "SOCORRO", codigo_departamento: 68 },
  { cityCode: 68770, cityName: "SUAITA", codigo_departamento: 68 },
  { cityCode: 68773, cityName: "SUCRE", codigo_departamento: 68 },
  { cityCode: 68780, cityName: "SURATA", codigo_departamento: 68 },
  { cityCode: 68820, cityName: "TONA", codigo_departamento: 68 },
  {
    cityCode: 68855,
    cityName: "VALLE DE SAN JOSE",
    codigo_departamento: 68,
  },
  { cityCode: 68861, cityName: "VELEZ", codigo_departamento: 68 },
  { cityCode: 68867, cityName: "VETAS", codigo_departamento: 68 },
  {
    cityCode: 68872,
    cityName: "VILLANUEVA",
    codigo_departamento: 68,
  },
  { cityCode: 68895, cityName: "ZAPATOCA", codigo_departamento: 68 },
  { cityCode: 70001, cityName: "SINCELEJO", codigo_departamento: 70 },
  {
    cityCode: 70110,
    cityName: "BUENAVISTA",
    codigo_departamento: 70,
  },
  { cityCode: 70124, cityName: "CAIMITO", codigo_departamento: 70 },
  { cityCode: 70204, cityName: "COLOSO", codigo_departamento: 70 },
  { cityCode: 70215, cityName: "COROZAL", codigo_departamento: 70 },
  { cityCode: 70221, cityName: "COVEÑAS", codigo_departamento: 70 },
  { cityCode: 70230, cityName: "CHALAN", codigo_departamento: 70 },
  { cityCode: 70233, cityName: "EL ROBLE", codigo_departamento: 70 },
  { cityCode: 70235, cityName: "GALERAS", codigo_departamento: 70 },
  { cityCode: 70265, cityName: "GUARANDA", codigo_departamento: 70 },
  { cityCode: 70400, cityName: "LA UNION", codigo_departamento: 70 },
  {
    cityCode: 70418,
    cityName: "LOS PALMITOS",
    codigo_departamento: 70,
  },
  { cityCode: 70429, cityName: "MAJAGUAL", codigo_departamento: 70 },
  { cityCode: 70473, cityName: "MORROA", codigo_departamento: 70 },
  { cityCode: 70508, cityName: "OVEJAS", codigo_departamento: 70 },
  { cityCode: 70523, cityName: "PALMITO", codigo_departamento: 70 },
  { cityCode: 70670, cityName: "SAMPUES", codigo_departamento: 70 },
  {
    cityCode: 70678,
    cityName: "SAN BENITO ABAD",
    codigo_departamento: 70,
  },
  {
    cityCode: 70702,
    cityName: "SAN JUAN DE BETULIA",
    codigo_departamento: 70,
  },
  {
    cityCode: 70708,
    cityName: "SAN MARCOS",
    codigo_departamento: 70,
  },
  {
    cityCode: 70713,
    cityName: "SAN ONOFRE",
    codigo_departamento: 70,
  },
  { cityCode: 70717, cityName: "SAN PEDRO", codigo_departamento: 70 },
  {
    cityCode: 70742,
    cityName: "SAN LUIS DE SINCE",
    codigo_departamento: 70,
  },
  { cityCode: 70771, cityName: "SUCRE", codigo_departamento: 70 },
  {
    cityCode: 70820,
    cityName: "SANTIAGO DE TOLU",
    codigo_departamento: 70,
  },
  {
    cityCode: 70823,
    cityName: "SAN JOSE DE TOLUVIEJO",
    codigo_departamento: 70,
  },
  { cityCode: 73001, cityName: "IBAGUE", codigo_departamento: 73 },
  { cityCode: 73024, cityName: "ALPUJARRA", codigo_departamento: 73 },
  { cityCode: 73026, cityName: "ALVARADO", codigo_departamento: 73 },
  { cityCode: 73030, cityName: "AMBALEMA", codigo_departamento: 73 },
  {
    cityCode: 73043,
    cityName: "ANZOATEGUI",
    codigo_departamento: 73,
  },
  { cityCode: 73055, cityName: "ARMERO", codigo_departamento: 73 },
  { cityCode: 73067, cityName: "ATACO", codigo_departamento: 73 },
  { cityCode: 73124, cityName: "CAJAMARCA", codigo_departamento: 73 },
  {
    cityCode: 73148,
    cityName: "CARMEN DE APICALA",
    codigo_departamento: 73,
  },
  {
    cityCode: 73152,
    cityName: "CASABIANCA",
    codigo_departamento: 73,
  },
  { cityCode: 73168, cityName: "CHAPARRAL", codigo_departamento: 73 },
  { cityCode: 73200, cityName: "COELLO", codigo_departamento: 73 },
  { cityCode: 73217, cityName: "COYAIMA", codigo_departamento: 73 },
  { cityCode: 73226, cityName: "CUNDAY", codigo_departamento: 73 },
  { cityCode: 73236, cityName: "DOLORES", codigo_departamento: 73 },
  { cityCode: 73268, cityName: "ESPINAL", codigo_departamento: 73 },
  { cityCode: 73270, cityName: "FALAN", codigo_departamento: 73 },
  { cityCode: 73275, cityName: "FLANDES", codigo_departamento: 73 },
  { cityCode: 73283, cityName: "FRESNO", codigo_departamento: 73 },
  { cityCode: 73319, cityName: "GUAMO", codigo_departamento: 73 },
  { cityCode: 73347, cityName: "HERVEO", codigo_departamento: 73 },
  { cityCode: 73349, cityName: "HONDA", codigo_departamento: 73 },
  { cityCode: 73352, cityName: "ICONONZO", codigo_departamento: 73 },
  { cityCode: 73408, cityName: "LERIDA", codigo_departamento: 73 },
  { cityCode: 73411, cityName: "LIBANO", codigo_departamento: 73 },
  {
    cityCode: 73443,
    cityName: "SAN SEBASTIAN DE MARIQUITA",
    codigo_departamento: 73,
  },
  { cityCode: 73449, cityName: "MELGAR", codigo_departamento: 73 },
  { cityCode: 73461, cityName: "MURILLO", codigo_departamento: 73 },
  { cityCode: 73483, cityName: "NATAGAIMA", codigo_departamento: 73 },
  { cityCode: 73504, cityName: "ORTEGA", codigo_departamento: 73 },
  {
    cityCode: 73520,
    cityName: "PALOCABILDO",
    codigo_departamento: 73,
  },
  { cityCode: 73547, cityName: "PIEDRAS", codigo_departamento: 73 },
  { cityCode: 73555, cityName: "PLANADAS", codigo_departamento: 73 },
  { cityCode: 73563, cityName: "PRADO", codigo_departamento: 73 },
  {
    cityCode: 73585,
    cityName: "PURIFICACION",
    codigo_departamento: 73,
  },
  { cityCode: 73616, cityName: "RIOBLANCO", codigo_departamento: 73 },
  {
    cityCode: 73622,
    cityName: "RONCESVALLES",
    codigo_departamento: 73,
  },
  { cityCode: 73624, cityName: "ROVIRA", codigo_departamento: 73 },
  { cityCode: 73671, cityName: "SALDAÑA", codigo_departamento: 73 },
  {
    cityCode: 73675,
    cityName: "SAN ANTONIO",
    codigo_departamento: 73,
  },
  { cityCode: 73678, cityName: "SAN LUIS", codigo_departamento: 73 },
  {
    cityCode: 73686,
    cityName: "SANTA ISABEL",
    codigo_departamento: 73,
  },
  { cityCode: 73770, cityName: "SUAREZ", codigo_departamento: 73 },
  {
    cityCode: 73854,
    cityName: "VALLE DE SAN JUAN",
    codigo_departamento: 73,
  },
  { cityCode: 73861, cityName: "VENADILLO", codigo_departamento: 73 },
  {
    cityCode: 73870,
    cityName: "VILLAHERMOSA",
    codigo_departamento: 73,
  },
  {
    cityCode: 73873,
    cityName: "VILLARRICA",
    codigo_departamento: 73,
  },
  { cityCode: 76001, cityName: "CALI", codigo_departamento: 76 },
  { cityCode: 76020, cityName: "ALCALA", codigo_departamento: 76 },
  { cityCode: 76036, cityName: "ANDALUCIA", codigo_departamento: 76 },
  {
    cityCode: 76041,
    cityName: "ANSERMANUEVO",
    codigo_departamento: 76,
  },
  { cityCode: 76054, cityName: "ARGELIA", codigo_departamento: 76 },
  { cityCode: 76100, cityName: "BOLIVAR", codigo_departamento: 76 },
  {
    cityCode: 76109,
    cityName: "BUENAVENTURA",
    codigo_departamento: 76,
  },
  {
    cityCode: 76111,
    cityName: "GUADALAJARA DE BUGA",
    codigo_departamento: 76,
  },
  {
    cityCode: 76113,
    cityName: "BUGALAGRANDE",
    codigo_departamento: 76,
  },
  {
    cityCode: 76122,
    cityName: "CAICEDONIA",
    codigo_departamento: 76,
  },
  { cityCode: 76126, cityName: "CALIMA", codigo_departamento: 76 },
  {
    cityCode: 76130,
    cityName: "CANDELARIA",
    codigo_departamento: 76,
  },
  { cityCode: 76147, cityName: "CARTAGO", codigo_departamento: 76 },
  { cityCode: 76233, cityName: "DAGUA", codigo_departamento: 76 },
  { cityCode: 76243, cityName: "EL AGUILA", codigo_departamento: 76 },
  { cityCode: 76246, cityName: "EL CAIRO", codigo_departamento: 76 },
  {
    cityCode: 76248,
    cityName: "EL CERRITO",
    codigo_departamento: 76,
  },
  { cityCode: 76250, cityName: "EL DOVIO", codigo_departamento: 76 },
  { cityCode: 76275, cityName: "FLORIDA", codigo_departamento: 76 },
  { cityCode: 76306, cityName: "GINEBRA", codigo_departamento: 76 },
  { cityCode: 76318, cityName: "GUACARI", codigo_departamento: 76 },
  { cityCode: 76364, cityName: "JAMUNDI", codigo_departamento: 76 },
  { cityCode: 76377, cityName: "LA CUMBRE", codigo_departamento: 76 },
  { cityCode: 76400, cityName: "LA UNION", codigo_departamento: 76 },
  {
    cityCode: 76403,
    cityName: "LA VICTORIA",
    codigo_departamento: 76,
  },
  { cityCode: 76497, cityName: "OBANDO", codigo_departamento: 76 },
  { cityCode: 76520, cityName: "PALMIRA", codigo_departamento: 76 },
  { cityCode: 76563, cityName: "PRADERA", codigo_departamento: 76 },
  { cityCode: 76606, cityName: "RESTREPO", codigo_departamento: 76 },
  { cityCode: 76616, cityName: "RIOFRIO", codigo_departamento: 76 },
  {
    cityCode: 76622,
    cityName: "ROLDANILLO",
    codigo_departamento: 76,
  },
  { cityCode: 76670, cityName: "SAN PEDRO", codigo_departamento: 76 },
  { cityCode: 76736, cityName: "SEVILLA", codigo_departamento: 76 },
  { cityCode: 76823, cityName: "TORO", codigo_departamento: 76 },
  { cityCode: 76828, cityName: "TRUJILLO", codigo_departamento: 76 },
  { cityCode: 76834, cityName: "TULUA", codigo_departamento: 76 },
  { cityCode: 76845, cityName: "ULLOA", codigo_departamento: 76 },
  { cityCode: 76863, cityName: "VERSALLES", codigo_departamento: 76 },
  { cityCode: 76869, cityName: "VIJES", codigo_departamento: 76 },
  { cityCode: 76890, cityName: "YOTOCO", codigo_departamento: 76 },
  { cityCode: 76892, cityName: "YUMBO", codigo_departamento: 76 },
  { cityCode: 76895, cityName: "ZARZAL", codigo_departamento: 76 },
  { cityCode: 81001, cityName: "ARAUCA", codigo_departamento: 81 },
  { cityCode: 81065, cityName: "ARAUQUITA", codigo_departamento: 81 },
  {
    cityCode: 81220,
    cityName: "CRAVO NORTE",
    codigo_departamento: 81,
  },
  { cityCode: 81300, cityName: "FORTUL", codigo_departamento: 81 },
  {
    cityCode: 81591,
    cityName: "PUERTO RONDON",
    codigo_departamento: 81,
  },
  { cityCode: 81736, cityName: "SARAVENA", codigo_departamento: 81 },
  { cityCode: 81794, cityName: "TAME", codigo_departamento: 81 },
  { cityCode: 85001, cityName: "YOPAL", codigo_departamento: 85 },
  { cityCode: 85010, cityName: "AGUAZUL", codigo_departamento: 85 },
  { cityCode: 85015, cityName: "CHAMEZA", codigo_departamento: 85 },
  {
    cityCode: 85125,
    cityName: "HATO COROZAL",
    codigo_departamento: 85,
  },
  { cityCode: 85136, cityName: "LA SALINA", codigo_departamento: 85 },
  { cityCode: 85139, cityName: "MANI", codigo_departamento: 85 },
  { cityCode: 85162, cityName: "MONTERREY", codigo_departamento: 85 },
  { cityCode: 85225, cityName: "NUNCHIA", codigo_departamento: 85 },
  { cityCode: 85230, cityName: "OROCUE", codigo_departamento: 85 },
  {
    cityCode: 85250,
    cityName: "PAZ DE ARIPORO",
    codigo_departamento: 85,
  },
  { cityCode: 85263, cityName: "PORE", codigo_departamento: 85 },
  { cityCode: 85279, cityName: "RECETOR", codigo_departamento: 85 },
  {
    cityCode: 85300,
    cityName: "SABANALARGA",
    codigo_departamento: 85,
  },
  { cityCode: 85315, cityName: "SACAMA", codigo_departamento: 85 },
  {
    cityCode: 85325,
    cityName: "SAN LUIS DE PALENQUE",
    codigo_departamento: 85,
  },
  { cityCode: 85400, cityName: "TAMARA", codigo_departamento: 85 },
  { cityCode: 85410, cityName: "TAURAMENA", codigo_departamento: 85 },
  { cityCode: 85430, cityName: "TRINIDAD", codigo_departamento: 85 },
  {
    cityCode: 85440,
    cityName: "VILLANUEVA",
    codigo_departamento: 85,
  },
  { cityCode: 86001, cityName: "MOCOA", codigo_departamento: 86 },
  { cityCode: 86219, cityName: "COLON", codigo_departamento: 86 },
  { cityCode: 86320, cityName: "ORITO", codigo_departamento: 86 },
  {
    cityCode: 86568,
    cityName: "PUERTO ASIS",
    codigo_departamento: 86,
  },
  {
    cityCode: 86569,
    cityName: "PUERTO CAICEDO",
    codigo_departamento: 86,
  },
  {
    cityCode: 86571,
    cityName: "PUERTO GUZMAN",
    codigo_departamento: 86,
  },
  {
    cityCode: 86573,
    cityName: "PUERTO LEGUIZAMO",
    codigo_departamento: 86,
  },
  { cityCode: 86749, cityName: "SIBUNDOY", codigo_departamento: 86 },
  {
    cityCode: 86755,
    cityName: "SAN FRANCISCO",
    codigo_departamento: 86,
  },
  {
    cityCode: 86757,
    cityName: "SAN MIGUEL",
    codigo_departamento: 86,
  },
  { cityCode: 86760, cityName: "SANTIAGO", codigo_departamento: 86 },
  {
    cityCode: 86865,
    cityName: "VALLE DEL GUAMUEZ",
    codigo_departamento: 86,
  },
  {
    cityCode: 86885,
    cityName: "VILLAGARZON",
    codigo_departamento: 86,
  },
  {
    cityCode: 88001,
    cityName: "SAN ANDRES",
    codigo_departamento: 88,
  },
  {
    cityCode: 88564,
    cityName: "PROVIDENCIA",
    codigo_departamento: 88,
  },
  { cityCode: 91001, cityName: "LETICIA", codigo_departamento: 91 },
  {
    cityCode: 91263,
    cityName: "EL ENCANTO",
    codigo_departamento: 91,
  },
  {
    cityCode: 91405,
    cityName: "LA CHORRERA",
    codigo_departamento: 91,
  },
  {
    cityCode: 91407,
    cityName: "LA PEDRERA",
    codigo_departamento: 91,
  },
  {
    cityCode: 91430,
    cityName: "LA VICTORIA",
    codigo_departamento: 91,
  },
  {
    cityCode: 91460,
    cityName: "MIRITI - PARANA",
    codigo_departamento: 91,
  },
  {
    cityCode: 91530,
    cityName: "PUERTO ALEGRIA",
    codigo_departamento: 91,
  },
  {
    cityCode: 91536,
    cityName: "PUERTO ARICA",
    codigo_departamento: 91,
  },
  {
    cityCode: 91540,
    cityName: "PUERTO NARIÑO",
    codigo_departamento: 91,
  },
  {
    cityCode: 91669,
    cityName: "PUERTO SANTANDER",
    codigo_departamento: 91,
  },
  { cityCode: 91798, cityName: "TARAPACA", codigo_departamento: 91 },
  { cityCode: 94001, cityName: "INIRIDA", codigo_departamento: 94 },
  {
    cityCode: 94343,
    cityName: "BARRANCOMINAS",
    codigo_departamento: 94,
  },
  {
    cityCode: 94883,
    cityName: "SAN FELIPE",
    codigo_departamento: 94,
  },
  {
    cityCode: 94884,
    cityName: "PUERTO COLOMBIA",
    codigo_departamento: 94,
  },
  {
    cityCode: 94885,
    cityName: "LA GUADALUPE",
    codigo_departamento: 94,
  },
  { cityCode: 94886, cityName: "CACAHUAL", codigo_departamento: 94 },
  { cityCode: 94887, cityName: "PANA PANA", codigo_departamento: 94 },
  { cityCode: 94888, cityName: "MORICHAL", codigo_departamento: 94 },
  {
    cityCode: 95001,
    cityName: "SAN JOSE DEL GUAVIARE",
    codigo_departamento: 95,
  },
  { cityCode: 95015, cityName: "CALAMAR", codigo_departamento: 95 },
  {
    cityCode: 95025,
    cityName: "EL RETORNO",
    codigo_departamento: 95,
  },
  {
    cityCode: 95200,
    cityName: "MIRAFLORES",
    codigo_departamento: 95,
  },
  { cityCode: 97001, cityName: "MITU", codigo_departamento: 97 },
  { cityCode: 97161, cityName: "CARURU", codigo_departamento: 97 },
  { cityCode: 97511, cityName: "PACOA", codigo_departamento: 97 },
  { cityCode: 97666, cityName: "TARAIRA", codigo_departamento: 97 },
  { cityCode: 97777, cityName: "PAPUNAHUA", codigo_departamento: 97 },
  { cityCode: 97889, cityName: "YAVARATE", codigo_departamento: 97 },
  {
    cityCode: 99001,
    cityName: "PUERTO CARREÑO",
    codigo_departamento: 99,
  },
  {
    cityCode: 99524,
    cityName: "LA PRIMAVERA",
    codigo_departamento: 99,
  },
  {
    cityCode: 99624,
    cityName: "SANTA ROSALIA",
    codigo_departamento: 99,
  },
  { cityCode: 99773, cityName: "CUMARIBO", codigo_departamento: 99 },
];
